### PR TITLE
Fix await_consistency

### LINKED ISSUE #4519: Verify behavior of `await_consistency`
See the questions raised by this PR -> https://github.com/holochain/holochain/pull/4509

### PR DESCRIPTION
**Pull request by jost-s**
### Summary

Centerpiece of a lot of integration tests, `await_consistency` wasn't perfectly stable. And far from straightforward to understand. I've rewritten it in the simplest way I could think of, when all peer DHT DBs have the sum of all ops integrated.

It may happen now that we'll have more flaky test cases. I'm happy to look into them. Unless there's something wrong with the logic of this function.

There was `await_consistency_advanced`, which I moved to a separate module which is behind the features `unstable-functions` or `unstable-warrants` like the only 3 tests that use that function.

This is what the new report looks like:
```
Consistency not reached.

Agent 0 with key uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM has the following ops in the DHT DB:
Author                                                 Action seq  Op type                Op hash                                                Integrated
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           0  StoreRecord            uhCQk_G_XvTCOS_9E71VCGDcqgc2d6UM1UGofSMawtpdIoixPA-89  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           0  RegisterAgentActivity  uhCQkKne7mg-uyGIcfnw0Zd4ikWgS1-MAqenbXxF1WrYoFm-4JYPT  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           1  StoreRecord            uhCQkco_QqMYn0grxbLXbD-lkopzw_Xv-5LdOKwMUR3hm5Mju6Qpr  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           1  RegisterAgentActivity  uhCQkRoC2nLO7Eyj4x-LAYl0YUqxy3b87yM9CpzlOMxEftc4ExUHj  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           2  StoreRecord            uhCQkRExn-hYlBZUGAFeXXg_sPQosX6WHhwXqGtGASweyz7KjSU9a  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           2  RegisterAgentActivity  uhCQkHvUPn7drW1Qhk6gYovKsMzMXCJ4CudtIawnkLvMPnp3wpfe4  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           2  StoreEntry             uhCQkgtb7TjIvG08Ii-MoC1jBSxvXVON6e-riLS5tQ7GEl92YD7wt  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           3  StoreRecord            uhCQkk2K0pj88ruOLUlhNNK7rrzcTMJYg6SVuY_2ZD0NrNRCpEzVA  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           3  RegisterAgentActivity  uhCQksewXeLyKKB-u7MCForDXi0buUo-1wcfenD0x6I1SaPey-NxB  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           4  StoreRecord            uhCQk4xakj_amuYhPE7azlp2U9uhPPUzosZZ7sXWNkKa3LD8zX3TT  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           4  RegisterAgentActivity  uhCQk4-A7gAGvWXXgehvRs0GKlD2qsxxx8aLATUYyCEamGT68ov2G  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           4  StoreEntry             uhCQkgLW6P7IhEv9D6bFWTiwZYtAIjAOsQF6zWojeG_ei-wj2_-1d  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           0  StoreRecord            uhCQkKQmOqpfEnFFGyD8g9gw5bcyecdxtO9EuR6KjCMO0MhLWOgNS  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           0  RegisterAgentActivity  uhCQkK_7pQUeblod0krCUS3PUP-yhkjFmf22LqSGewdWnDH9zRd2C  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           1  StoreRecord            uhCQkQh_Esoo--B_sGxutz-lG3J9O8K9wCpa66Hz09LNeBy-wABM5  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           1  RegisterAgentActivity  uhCQkDSCB4BGrdw6pFtxjGpzcmEGgKX-AA4-Y8kQOc8SazUklIIQP  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           2  StoreRecord            uhCQkUIMtGRvjL2NpacCHI3K48qQK1Gt4QefatvPMgCLPunVQZd7p  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           2  StoreEntry             uhCQkjlL57rnQ0BLuwZCJIByJGHaJZuISnlF5JSBtsuas0sWlstcn  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           2  RegisterAgentActivity  uhCQkuQ9qUiuCrVJw1bhM5vYNEhz2a7R9NozwojIxm7mJD7j9hi7y  true      

Agent 1 with key uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H has the following ops in the DHT DB:
Author                                                 Action seq  Op type                Op hash                                                Integrated
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           0  StoreRecord            uhCQk_G_XvTCOS_9E71VCGDcqgc2d6UM1UGofSMawtpdIoixPA-89  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           0  RegisterAgentActivity  uhCQkKne7mg-uyGIcfnw0Zd4ikWgS1-MAqenbXxF1WrYoFm-4JYPT  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           1  StoreRecord            uhCQkco_QqMYn0grxbLXbD-lkopzw_Xv-5LdOKwMUR3hm5Mju6Qpr  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           1  RegisterAgentActivity  uhCQkRoC2nLO7Eyj4x-LAYl0YUqxy3b87yM9CpzlOMxEftc4ExUHj  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           2  RegisterAgentActivity  uhCQkHvUPn7drW1Qhk6gYovKsMzMXCJ4CudtIawnkLvMPnp3wpfe4  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           2  StoreRecord            uhCQkRExn-hYlBZUGAFeXXg_sPQosX6WHhwXqGtGASweyz7KjSU9a  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           2  StoreEntry             uhCQkgtb7TjIvG08Ii-MoC1jBSxvXVON6e-riLS5tQ7GEl92YD7wt  true      
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           3  RegisterAgentActivity  uhCQksewXeLyKKB-u7MCForDXi0buUo-1wcfenD0x6I1SaPey-NxB  false     
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           3  StoreRecord            uhCQkk2K0pj88ruOLUlhNNK7rrzcTMJYg6SVuY_2ZD0NrNRCpEzVA  false     
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           4  RegisterAgentActivity  uhCQk4-A7gAGvWXXgehvRs0GKlD2qsxxx8aLATUYyCEamGT68ov2G  false     
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           4  StoreEntry             uhCQkgLW6P7IhEv9D6bFWTiwZYtAIjAOsQF6zWojeG_ei-wj2_-1d  false     
uhCAkbtoNnv5f_T4p7harzVDuRTr931OYflFR0yc2EyNQsvuaxiHM           4  StoreRecord            uhCQk4xakj_amuYhPE7azlp2U9uhPPUzosZZ7sXWNkKa3LD8zX3TT  false     
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           0  StoreRecord            uhCQkKQmOqpfEnFFGyD8g9gw5bcyecdxtO9EuR6KjCMO0MhLWOgNS  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           0  RegisterAgentActivity  uhCQkK_7pQUeblod0krCUS3PUP-yhkjFmf22LqSGewdWnDH9zRd2C  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           1  StoreRecord            uhCQkQh_Esoo--B_sGxutz-lG3J9O8K9wCpa66Hz09LNeBy-wABM5  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           1  RegisterAgentActivity  uhCQkDSCB4BGrdw6pFtxjGpzcmEGgKX-AA4-Y8kQOc8SazUklIIQP  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           2  StoreRecord            uhCQkUIMtGRvjL2NpacCHI3K48qQK1Gt4QefatvPMgCLPunVQZd7p  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           2  RegisterAgentActivity  uhCQkuQ9qUiuCrVJw1bhM5vYNEhz2a7R9NozwojIxm7mJD7j9hi7y  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           2  StoreEntry             uhCQkjlL57rnQ0BLuwZCJIByJGHaJZuISnlF5JSBtsuas0sWlstcn  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           3  StoreRecord            uhCQkpOBVtMGntN06Qr_2SEk8IJ9QQI0IPUE-gm3NtfgueSqSp3II  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           3  RegisterAgentActivity  uhCQkhDWyTAjDz9TVGxGIsky8_WkU-iDcPrpZeUWII-zFdwB5Gf7N  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           4  StoreRecord            uhCQkziYwjymtoJ4f7Y6M4dgrt5MYlWzdBLgxEF-1rJNaV6ax5YX-  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           4  RegisterAgentActivity  uhCQk-FY3Fh2TFn25ZuNYFXrEBmmixIShAT5Gyx_g2QXdN4b53722  true      
uhCAk_Cge7xM5Ou8f1XF-Z4QOMjfHTZhsDTTbJzy23blDLytpgX4H           4  StoreEntry             uhCQk44c2fXZMovgQ1Yuw-YXnkymJdlJEgHtU6i2f7oHchi_kuEko  true 
```

resolves #4519 

### TODO:
- [x] CHANGELOGs updated with appropriate info
- [x] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

File: crates/holochain/src/test_utils.rs [hunk 1]
```diff
@@ -257,302 +255,6 @@ pub fn warm_wasm_tests() {
     }
 }
 
-/// Consistency was failed to be reached. Here's a report.
```
Comment (jost-s) [inline crates/holochain/src/test_utils.rs:260]: All of this is moved to the `conditional_consistency` module.

File: crates/holochain/src/sweettest/sweet_consistency.rs [hunk 2]
```diff
@@ -32,60 +32,174 @@ impl DurationOrSeconds {
...
-        .collect();
-    wait_for_integration_diff(
-        &all_cell_dbs[..],
-        timeout.into().into_duration(),
-        conditions.into(),
-    )
-    .await
+/// Wait for all cell envs to reach consistency, meaning that every op
+/// published by every cell has been integrated by every node.
+async fn await_op_integration(
```
Comment (jost-s) [inline crates/holochain/src/sweettest/sweet_consistency.rs:56]: This used to be `wait_for_integration_diff`. Moved here and renamed and rewritten.

File: crates/holochain/src/sweettest/sweet_consistency.rs [hunk 3]
```diff
@@ -32,60 +32,174 @@ impl DurationOrSeconds {
...
+                        index,
+                        cells[index].0,
+                        dht_op_rows.len()
+                    );
+                    let mut hash_list = Vec::new();
+                    for row in dht_op_rows {
+                        // If any op is not yet integrated, continue to the next loop iteration.
+                        if row.when_integrated.is_none() {
+                            tracing::trace!("Unintegrated op found, sleeping...");
+                            continue;
```
Comment (mattyg) [inline crates/holochain/src/sweettest/sweet_consistency.rs:121]: This `continue` applies to the most deeply-nested for loop, right? In that case it doesn't look like its sleeping so that can be removed from the trace log.

Or is this intended to apply to the top level `loop`, in which case I think we need to use a loop label to specify that.

File: crates/holochain/src/sweettest/sweet_consistency.rs [hunk 4]
```diff
@@ -32,60 +32,174 @@ impl DurationOrSeconds {
...
+                            FROM DhtOp
+                            JOIN Action ON DhtOp.action_hash = Action.hash",
+                        )
+                        .unwrap();
+                    let mut rows = stmt.query([]).unwrap();
+                    let mut values = Vec::new();
+                    while let Some(row) = rows.next().unwrap() {
+                        let hash = row.get_unwrap::<_, DhtOpHash>(0);
+                        let op_type = row.get_unwrap::<_, DhtOpType>(1);
+                        let when_integrated = row.get_unwrap::<_, Option<Timestamp>>(2);
```
Comment (mattyg) [inline crates/holochain/src/sweettest/sweet_consistency.rs:82]: Read my next comment first, so if this doesn't make sense ignore it.

Should we `continue` the loop up here if `when_integrated` is None? Since (I think) we're trying to do the same thing later after more work?

Comment (jost-s) [reply crates/holochain/src/sweettest/sweet_consistency.rs:82]: Nice catch! Yes, that continue was ineffective. continues aren't allowed inside of closure or functions, so I can't put that here. It's not much more work, because these futures defined here are executed a little further down and then already iterated over. I've applied the loop label in the other position.

**Review by mattyg — APPROVED** [review]

**Comment by mattyg** [comment]
Not sure if there's a straightforward way we could put some tests on this function. It is quite an important one.

**Comment by jost-s** [comment]
I've added 3 tests to cover successful consistency with private and public entries and unsuccessful consistency. These tests are full integration tests and slow, so I don't want to add more. Also I can't think of more relevant test cases. There are like 50 occurrences of the function, that's a good test suite.

File: crates/holochain/src/sweettest/sweet_consistency.rs [hunk 5]
```diff
@@ -32,60 +32,271 @@ impl DurationOrSeconds {
...
+                "create_priv_msg",
+                (),
+            )
+            .await;
+
+        await_consistency(5, &[alice, bob]).await.unwrap();
+    }
+
+    #[tokio::test(flavor = "multi_thread")]
+    async fn consistency_not_reached() {
```
Comment (mattyg) [inline crates/holochain/src/sweettest/sweet_consistency.rs:285]: I don't follow this -- why is consistency not reached here?

Also wondering if we want 2 tests for consistency not reached: one where it an op is authored but not integrated, and another where an integrated op is not synced.

Comment (jost-s) [reply crates/holochain/src/sweettest/sweet_consistency.rs:285]: It's not reached because the timeout is too short with 1 second.

Comment (jost-s) [reply crates/holochain/src/sweettest/sweet_consistency.rs:285]: I've slightly updated the no consistency test and tried another one where ops are not integrated yet, but it's flaky. There's no way to prevent op integration in this full Holochain integration test.

Comment (jost-s) [reply crates/holochain/src/sweettest/sweet_consistency.rs]: There is a way though to directly write an op to the DHT DB. That's not integrated. Added the test for it.

**Review by ThetaSinner — APPROVED** [review]
Looks convincing, clear and sensibly performant! 

I think it might be nice to be able to choose how often this loops but otherwise nothing to query here :)

**Comment by jost-s** [comment]
@ThetaSinner The wishing counter is still open here: With which API would you like to choose the loop frequency?

**Comment by ThetaSinner** [comment]
Perhaps two functions, one that lets you configure the timing and one that lets you call the other function with some default parameters?

**Comment by jost-s** [comment]
Do you mean `fn await_consistency(timeout: impl Into<DurationOrSeconds>, cells: SweetCells)` and a new function
```rust
fn await_consistency_default(cells: SweetCells)` {
  await_concistency(20, cells)
}
```
?
