### PR TITLE
Remove app pause function and state

### LINKED ISSUE #5092: Remove pause app function and state
Apps are only paused when individual cells can't be started up and join the network or error for some other reason. Instead app enabling should just fail, so this state can be removed.

### PR DESCRIPTION
**Pull request by jost-s**
### Summary

resolves #5092 

### TODO:
- [x] CHANGELOGs updated with appropriate info
- [x] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

File: crates/holochain_types/src/app.rs [hunk 1]
```diff
@@ -406,7 +406,7 @@ impl From<RunningApp> for InstalledApp {
     }
 }
 
-/// An app which is either Paused or Disabled, i.e. not Running
+/// An app which is Disabled, i.e. not Running
```
Comment (veeso) [inline crates/holochain_types/src/app.rs]: If this is related to `AppStatus::Disabled`, to help users navigate the documentation, you could change to "[`AppStatus::Disabled`]".

File: crates/holochain/CHANGELOG.md [hunk 2]
```diff
@@ -9,6 +9,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 - Test app operations (install/enable/disable/uninstall) with regards to app state and cell state.
 - **BREAKING CHANGE**: Remove `start_app` from conductor. Use `enable_app` instead.
+- **BREAKING CHANGE**: Remove `pause_app` and `Paused` state from conductor. Pausing an app was used when enabling an app partially failed and could be re-attempted. Now the app is only enabled if all cells successfully started up.
```
Comment (veeso) [inline crates/holochain/CHANGELOG.md:18]: If this is a breaking change, the commit message should not be a `chore` by convention, I think, but it should be either a feat or fix with the breaking flag `!`

File: crates/holochain/src/conductor/conductor.rs [hunk 3]
```diff
@@ -394,7 +394,7 @@ mod startup_shutdown_impls {
 
             // We don't care what fx are returned here, since all cells need to
             // be spun up
-            let _ = self.start_paused_apps().await?;
+            let _ = self.start_apps().await?;
```
Comment (matthme) [inline crates/holochain/src/conductor/conductor.rs]: I haven't looked into the code deeply yet but that doesn't seem correct to me here. I don't think we want to start stopped apps when initializing the conductor as these include apps that have been deliberately disabled by the user. Do we have a test that checks that an app can be disabled via the adminwebsocket and won't get automatically re-enabled on conductor restart?

File: crates/holochain/src/conductor/conductor.rs [hunk 4]
```diff
@@ -721,10 +721,10 @@ mod dna_impls {
 
         /// Restart every paused app
         #[cfg_attr(feature = "instrument", tracing::instrument(skip_all))]
-        pub(crate) async fn start_paused_apps(&self) -> ConductorResult<AppStatusFx> {
+        pub(crate) async fn start_apps(&self) -> ConductorResult<AppStatusFx> {
```
Comment (matthme) [inline crates/holochain/src/conductor/conductor.rs]: If this function is starting stopped apps I would prefer it would be called `start_stopped_apps()`, otherwise it sounds like it is starting all apps. Or is this what it's doing?

File: crates/holochain/CHANGELOG.md (hunk 2 above)
Comment (jost-s) [reply crates/holochain/CHANGELOG.md:18]: Good point, it definitely needs the `!`. In the examples it seems that the commit type can also be `chore` with a breaking change: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer

File: crates/holochain/src/conductor/conductor.rs (hunk 3 above)
Comment (jost-s) [reply crates/holochain/src/conductor/conductor.rs]: see below

File: crates/holochain/src/conductor/conductor.rs (hunk 4 above)
Comment (jost-s) [reply crates/holochain/src/conductor/conductor.rs]: It is what it's doing. I'll rename it.

File: crates/holochain_types/src/app.rs (hunk 1 above)
Comment (jost-s) [reply crates/holochain_types/src/app.rs]: done

**Review by veeso — APPROVED** [review]

File: crates/holochain/src/conductor/conductor.rs (hunk 3 above)
Comment (matthme) [reply crates/holochain/src/conductor/conductor.rs]: I don't think my point has been addressed by renaming the function. I think we don't want to start stopped apps at all here is my point. Does that make sense? Or am I missing something?

Comment (jost-s) [reply crates/holochain/src/conductor/conductor.rs]: I see what you mean. Yeah, this is no longer applicable. Apps can't be paused, so they won't be started when initializing the conductor.

File: crates/holochain/src/conductor/conductor.rs [hunk 5]
```diff
@@ -721,10 +718,10 @@ mod dna_impls {
 
         /// Restart every paused app
         #[cfg_attr(feature = "instrument", tracing::instrument(skip_all))]
-        pub(crate) async fn start_paused_apps(&self) -> ConductorResult<AppStatusFx> {
+        pub(crate) async fn start_stopped_apps(&self) -> ConductorResult<AppStatusFx> {
```
Comment (ThetaSinner) [inline crates/holochain/src/conductor/conductor.rs]: Has the last usage of this not been removed above?

Semantically, starting a paused app is quite different from pausing a stopped app. We aren't distinguishing between failed to start and deliberately stopped by the user. I think that's fine but then we shouldn't just start all stopped apps, we should let the user selectively start the apps they want?

I think this can be removed, if it can't, I think it might make sense to try to remove it.

File: crates/holochain/src/conductor/conductor.rs [hunk 6]
```diff
@@ -2032,8 +2010,6 @@ mod app_status_impls {
         /// Adjust app statuses (via state transitions) to match the current
         /// reality of which Cells are present in the conductor.
         /// - Do not change state for Disabled apps. For all others:
-        /// - If an app is Paused but all of its (required) Cells are on,
-        ///   then set it to Running
         /// - If an app is Running but at least one of its (required) Cells are off,
         ///   then set it to Paused
```
Comment (ThetaSinner) [inline crates/holochain/src/conductor/conductor.rs]: Stopped?

File: crates/holochain_conductor_api/src/admin_interface.rs [hunk 7]
```diff
@@ -633,21 +633,12 @@ impl ExternalApiWireError {
...
+    /// Filter on apps which are Enabled.
     Enabled,
-    /// Filter only on apps which are Disabled.
+    /// Filter on apps which are Disabled.
     Disabled,
-    /// Filter on apps which are currently Running (meaning they are also Enabled).
-    Running,
-    /// Filter on apps which are Stopped, i.e. not Running.
-    /// This includes apps in the Disabled status, as well as the Paused status.
-    Stopped,
```
Comment (ThetaSinner) [inline crates/holochain_conductor_api/src/admin_interface.rs:648]: Ahh, I remember now. So stopped is a composite state and we should be removing references to "stopped" in favor of "disabled"

**Review by ThetaSinner — COMMENTED** [review]
Still finding the terminology a little confusing. If I'm following right the an installed app can either be enabled or disabled. An enabled app can either be running or stopped depending on whether its cells were able to start?

File: crates/holochain/src/conductor/conductor.rs (hunk 5 above)
Comment (matthme) [reply crates/holochain/src/conductor/conductor.rs]: Yes, I think it can be removed now that its usage has been removed in `initialize_conductor()` above.

File: crates/holochain_conductor_api/src/admin_interface.rs (hunk 7 above)
Comment (matthme) [reply crates/holochain_conductor_api/src/admin_interface.rs:648]: Actually, I'm seeing that the [StoppedAppReason](https://github.com/holochain/holochain/blob/a7ca376ac98d709c0594b52952696fe22ef54742/crates/holochain_types/src/app.rs#L1097-L1105) contains the `AwaitingMemproofs` variant which I'm not sure we can conflate with `Disabled` completely. But I'm also not entirely sure how `StoppedAppReason` relates to `AppStatusFilter`.

Comment (matthme) [reply crates/holochain_conductor_api/src/admin_interface.rs:648]: Maybe we don't need the `StoppedAppReason` enum at all anymore but in this case I think it should be removed as part of this PR.

File: crates/holochain/src/conductor/conductor.rs (hunk 6 above)
Comment (jost-s) [reply crates/holochain/src/conductor/conductor.rs]: Sure, I didn't bother much because all of those functions will be removed.

File: crates/holochain_conductor_api/src/admin_interface.rs (hunk 7 above)
Comment (jost-s) [reply crates/holochain_conductor_api/src/admin_interface.rs:648]: @matthme Did you mean to say "should not be"?

File: crates/holochain/src/conductor/conductor.rs (hunk 6 above)
Comment (ThetaSinner) [reply crates/holochain/src/conductor/conductor.rs]: Right, then this can be ignored.

File: crates/holochain_conductor_api/src/admin_interface.rs (hunk 7 above)
Comment (matthme) [reply crates/holochain_conductor_api/src/admin_interface.rs:648]: I meant that if we *don't* need `StoppedAppReason` anymore we might remove it as part of this PR.

**Comment by jost-s** [comment]
@matthme @ThetaSinner Thanks both of you for the hints. I've done another sweep and removed `stopped` and `started` as statuses and replaced with `disabled` and `enabled` where applicable in a separate commit.

It was well possible to include in this PR and not postpone until the bigger refactor.

Also `running ` is no longer a thing. There's just `enabled` and `disabled` now.

**Review by matthme — APPROVED** [review]
Looks good to me know :+1:

**Comment by jost-s** [comment]
Oops, I wanted to await @ThetaSinner's review. Please take a look.
