### PR TITLE
fix: trigger integration workflow after creating or revoking zome call capability

### LINKED ISSUE #5363: [BUG] Create and revoke cap grant DhtOps are not integrated until a subsequent zome call
**Describe the bug**
Upon creating a CapGrant, or revoking a CapGrant, their ops sit in integration limbo until a subsequent zome call triggers the integration workflow.

**Expected behavior**
The integration workflow is triggered after creating or revoking a cap grant.

### PR DESCRIPTION
**Pull request by mattyg**
### Summary
Resolves #5363 

### TODO:
- [x] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

## Summary by CodeRabbit

* **Improvements**
  * Integration workflow now automatically triggers after zome call capability grants and revocations.
  * Authored operations moved to limbo are now surfaced via notifications during grant/revoke handling.

* **Tests**
  * Added end-to-end tests for capability grant and revoke flows with explicit state-dump assertions and robust retry/wait handling to verify DHT integration.
  * Added integration tests verifying zome initialization and its idempotence.

* **Documentation**
  * Changelog updated to note the new integration trigger behavior.

### CODE REVIEW

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 1]
```diff
@@ -348,6 +348,100 @@ async fn cap_grant_info_call() {
         .lt(&cap_cell_info.revoked_at.unwrap()));
 }
 
+#[tokio::test(flavor = "multi_thread")]
+#[cfg(feature = "test_utils")]
+async fn grant_zome_call_capability_call() {
```
Comment (mattyg) [inline crates/holochain/src/conductor/tests/signed_zome_call.rs:352]: Previously, `grant_zome_call_capability` was only tested within the `revoke_zome_call_capability_call` test. Now it has its own test.

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 2]
```diff
@@ -348,6 +348,100 @@ async fn cap_grant_info_call() {
...
+    // 2 new DhtOps for cap grant are integrated into the source chain
+    let after_state_dump = conductor
+        .raw_handle()
+        .dump_full_cell_state(cell_id, None)
+        .await
+        .expect("Failed to get state dump");
+    assert_eq!(
+        after_state_dump.integration_dump.integrated.len()
+            - before_state_dump.integration_dump.integrated.len(),
+        2
```
Comment (mattyg) [inline crates/holochain/src/conductor/tests/signed_zome_call.rs:452]: Assert that 2 new dht ops have been integrated.

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 3]
```diff
@@ -442,4 +540,20 @@ async fn revoke_zome_call_capability_call() {
...
+    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
+
+    // 4 new DhtOps for cap grant revocation are integrated into the source chain
+    let after_state_dump = conductor
+        .raw_handle()
+        .dump_full_cell_state(cell_id, None)
+        .await
+        .expect("Failed to get state dump");
+    assert_eq!(
+        after_state_dump.integration_dump.integrated.len()
```
Comment (mattyg) [inline crates/holochain/src/conductor/tests/signed_zome_call.rs:664]: Assert that 4 new dht ops have been integrated

File: crates/holochain/src/conductor/cell.rs [hunk 4]
```diff
@@ -894,6 +894,10 @@ impl Cell {
         self.queue_triggers.countersigning.clone()
     }
 
+    pub(crate) fn integrate_dht_ops_trigger(&self) -> TriggerSender {
+        self.queue_triggers.integrate_dht_ops.clone()
+    }
```
[the remark this answers is not in the document]
Comment (mattyg) [reply crates/holochain/src/conductor/cell.rs]: fixed

Comment (ThetaSinner) [inline crates/holochain/src/conductor/cell.rs]: Why not use the method `notify_authored_ops_moved_to_limbo` defined above? That was added to expose the integration trigger behind a name that would be easy to trace when we deal with the problem of data being authored in multiple places outside of workflows.

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 5]
```diff
@@ -348,6 +348,100 @@ async fn cap_grant_info_call() {
         .lt(&cap_cell_info.revoked_at.unwrap()));
 }
 
+#[tokio::test(flavor = "multi_thread")]
+#[cfg(feature = "test_utils")]
```
Comment (ThetaSinner) [inline crates/holochain/src/conductor/tests/signed_zome_call.rs]: Suggest not gating behind `test_utils`, I think it's acceptable to assume that's always enabled for tests.

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 6]
```diff
@@ -348,6 +348,100 @@ async fn cap_grant_info_call() {
...
+        .expect("cap grant info is err")
+        .0
+        .first()
+        .unwrap()
+        .0
+        .clone();
+    assert_eq!(cap_grant_cell_id.clone(), cell_id.clone());
+
+    // Wait for integration workflow to complete
+    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
```
Comment (ThetaSinner) [inline crates/holochain/src/conductor/tests/signed_zome_call.rs]: Please avoid sleeping in tests, prefer a timeout-loop-check-sleep pattern instead. There are some helper functions for this or it can just be done directly.

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 7]
```diff
@@ -442,4 +540,20 @@ async fn revoke_zome_call_capability_call() {
     assert!(cap_cell_info
         .created_at
         .lt(&cap_cell_info.revoked_at.unwrap()));
+
+    // Wait for integration workflow to complete
+    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
```
Comment (ThetaSinner) [inline crates/holochain/src/conductor/tests/signed_zome_call.rs]: Same as above here, please timeout-loop-check-sleep

**Review by ThetaSinner — CHANGES_REQUESTED** [review]
Really nice find. The ongoing consequences of authoring data outside of workflows!

I'm requesting changes for two reasons:
- I think we can use an existing method to trigger integration
- Sleeping in tests can be improved

File: crates/holochain/src/conductor/tests/signed_zome_call.rs (hunk 6 above)
Comment (mattyg) [reply crates/holochain/src/conductor/tests/signed_zome_call.rs]: oops wasn't thinking - fixed https://github.com/holochain/holochain/pull/5364/commits/7926fb8c2cbf1c4311fb8f738486bbadcd518125

File: crates/holochain/src/conductor/tests/signed_zome_call.rs (hunk 7 above)
Comment (mattyg) [reply crates/holochain/src/conductor/tests/signed_zome_call.rs]: fixed https://github.com/holochain/holochain/pull/5364/commits/7926fb8c2cbf1c4311fb8f738486bbadcd518125

File: crates/holochain/src/conductor/tests/signed_zome_call.rs (hunk 5 above)
Comment (mattyg) [reply crates/holochain/src/conductor/tests/signed_zome_call.rs]: fixed https://github.com/holochain/holochain/pull/5364/commits/7926fb8c2cbf1c4311fb8f738486bbadcd518125

File: crates/holochain/src/conductor/cell.rs (hunk 4 above)
Comment (mattyg) [reply crates/holochain/src/conductor/cell.rs]: Great guess I missed it - fixed https://github.com/holochain/holochain/pull/5364/commits/9151d20a0edc9e0cc57d04985c3d37f07eac5fcb

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 8]
```diff
@@ -392,21 +491,34 @@ async fn revoke_zome_call_capability_call() {
...
         .expect("Failed to revoke zome call capability");
 
+    // Wait for integration workflow to complete
+    retry_fn_until_timeout(
+        || async { conductor.all_ops_integrated(dna.dna_hash()).unwrap() },
+        None,
+        None,
+    )
+    .await
+    .unwrap();
```
[the remark this answers is not in the document]
Comment (mattyg) [reply crates/holochain/src/conductor/tests/signed_zome_call.rs:617]: Very good, fixed: https://github.com/holochain/holochain/pull/5364/commits/520c9bcabdc3580c948425b7c40c8b2b113ab155

File: crates/holochain/src/conductor/tests/signed_zome_call.rs [hunk 9]
```diff
@@ -349,7 +350,105 @@ async fn cap_grant_info_call() {
...
+        .expect("failed to get cell");
+    cell.check_or_run_zome_init()
+        .await
+        .expect("failed to init cell");
+
+    let before_state_dump = conductor
+        .raw_handle()
+        .dump_full_cell_state(cell_id, None)
+        .await
+        .expect("Failed to get state dump");
```
[the remark this answers is not in the document]
Comment (mattyg) [reply crates/holochain/src/conductor/tests/signed_zome_call.rs:398]: fixed

**Comment by mattyg** [comment]
Added a few more tests:
- grant and revoke calls trigger zome initialization
- check_or_run_zome_init triggers zome initialization if not already initialized
