### PR TITLE
Fix: expand/correct documentation around `get_agent_activity` and `ChainQueryFilter`

### LINKED ISSUE #5235: [Chore] Fill out / improve Rustdoc for types related to getting agent activity
As a follow-up to [this comment](https://github.com/holochain/docs-pages/issues/537#issuecomment-3206307343), fill out details that are little more than stubs in structures like `AgentActivity` and `ActivityRequest` (so far these are the only ones I've found with terse/incomplete documentation).

### PR DESCRIPTION
**Pull request by pdaoust**
Closes #5235 .

### Summary

Corrects and expands on the RustDoc for `get_agent_activity` and all the other types that touch it.

### TODO:
- [ ] CHANGELOGs updated with appropriate info

## Summary by CodeRabbit

* **New Features**
  * Agent activity queries gain a request mode (Status or Full) and return richer details: chain status (Empty/Valid/Forked/Invalid), highest‑observed items, warrants, and matching action hashes when Full is requested.
  * Query filtering can toggle inclusion of entry data for matching actions.

* **Refactor**
  * Agent activity API now accepts an explicit request parameter to control returned data.

* **Documentation**
  * Clarified terminology (e.g., “action sequence”) and expanded guidance on status, warrants, and filtering behavior.

### CODE REVIEW

File: crates/hdk/src/chain.rs [hunk 1]
```diff
@@ -1,12 +1,31 @@
...
+/// * The highest observed chain item (or items, in the case of a chain fork),
+/// * A summary of whether the chain contains only valid items, contains at
+/// least one invalid item, is forked, or is empty,
+/// * Any warrants collected for invalid actions committed by the agent,
+/// * Sequence indices and action hashes of valid and rejected actions if
+/// desired (see [ `ActivityRequest::Full` ]).
 ///
-/// The agent activity can be filtered with [ `ChainQueryFilter` ] like a local chain query.
+/// The agent activity is held by the neighborhood of the agent's public key,
+/// rather than a content hash like the rest of the DHT.
```
Comment (mattyg) [inline crates/hdk/src/chain.rs]:
```suggestion
```

Link's aren't held at a content hash, just an arbitrary hash. I'd just leave it out.

File: crates/holochain_zome_types/src/query.rs [hunk 2]
```diff
@@ -78,7 +80,7 @@ pub struct ChainQueryFilter {
     // NB: if this filter is set, you can't verify the results, so don't
     //     use this in validation
     pub action_type: Option<Vec<ActionType>>,
-    /// Include the entries in the records
+    /// Include the entries in the records. This value is ignored for [ `get_agent_activity` ].
     pub include_entries: bool,
```
Comment (mattyg) [inline crates/holochain_zome_types/src/query.rs:86]: Huh, was this intentional design? Should it not be ignored?

File: crates/holochain_zome_types/src/query.rs [hunk 3]
```diff
@@ -108,41 +110,75 @@ pub struct LinkQuery {
...
+    /// Warrants received from other sources are not reflected in this field;
+    /// it simply contains actions whose [ `RegisterAgentActivity` ] operations
+    /// are valid.
     pub valid_activity: Vec<(u32, ActionHash)>,
-    /// Rejected actions on this chain. `(sequence, action_hash)`.
+    /// Rejected actions on this chain matching the filters passed to the
+    /// query, as a vector of `(sequence_index, action_hash)` tuples.  **Note**:
+    /// Warrants received from other sources are not reflected in this field;
+    /// it simply contains actions whose [ `RegisterAgentActivity` ] operations
+    /// are invalid.
```
Comment (mattyg) [inline crates/holochain_zome_types/src/query.rs]: Huh I see. Feels like more confusion arising from lacking a coherent concept of record validity.

**Review by mattyg — APPROVED** [review]
Oy a bit painful to see how convoluted our concept of validity is. But you've explained it much more clearly and explicitly. Thanks for that!

File: crates/hdk/src/chain.rs (hunk 1 above)
Comment (pdaoust) [reply crates/hdk/src/chain.rs]: yeah, I can't for the life of me remember why I put that in there -- I remember reading it and thinking "huh?"

File: crates/holochain_zome_types/src/query.rs (hunk 2 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs:86]: gooooooooooood question. It's unsupported all the way to the DHT op itself; check out [`ChainOp::RegisterAgentActivity`](https://docs.rs/holochain_types/latest/holochain_types/dht_op/enum.ChainOp.html#variant.RegisterAgentActivity), which doesn't even have a spot for the entry. So it's not so much that `get_agent_activity` ignores it; it's that it can't do anything with it.

File: crates/hdk/src/chain.rs [hunk 4]
```diff
@@ -1,12 +1,31 @@
...
-/// Query the _actions_ of a remote agent's chain.
+/// Query the current state of an agent's chain, including:
 ///
-/// The agent activity is only the actions of their source chain.
-/// The agent activity is held by the neighbourhood of the agent's public key, rather than a content hash like the rest of the DHT.
+/// * The highest observed chain item (or items, in the case of a chain fork),
+/// * A summary of whether the chain contains only valid items, contains at
+/// least one invalid item, is forked, or is empty,
+/// * Any warrants collected for invalid actions committed by the agent,
+/// * Sequence indices and action hashes of valid and rejected actions if
```
Comment (jost-s) [inline crates/hdk/src/chain.rs]: In the codebase sequence index isn't used anywhere.
```suggestion
/// * Action sequences and action hashes of valid and rejected actions if
```

File: crates/hdk/src/chain.rs [hunk 5]
```diff
@@ -1,12 +1,31 @@
...
+/// desired (see [ `ActivityRequest::Full` ]).
 ///
-/// The agent activity can be filtered with [ `ChainQueryFilter` ] like a local chain query.
+/// The agent activity is held by the neighborhood of the agent's public key,
+/// rather than a content hash like the rest of the DHT.
+///
+/// If retrieving chain items along with the current state using
+/// [ `ActivityRequest::Full` ], the chain items can be filtered with
+/// [ `ChainQueryFilter` ] like a local chain query. This filtering happens at
+/// the source before it sends the data to the receiver.
```
Comment (jost-s) [inline crates/hdk/src/chain.rs]: I think that kind of filtering is implicitly expected.
```suggestion
/// [ `ChainQueryFilter` ] like a local chain query.
```

File: crates/holochain_zome_types/src/query.rs (hunk 2 above)
Comment (jost-s) [reply crates/holochain_zome_types/src/query.rs:86]: Agent activity ops don't include entries. There should better be a separate query filter for get_agent_activity without this option.

File: crates/holochain_zome_types/src/query.rs [hunk 6]
```diff
@@ -108,41 +110,75 @@ pub struct LinkQuery {
 }
 
 #[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, SerializedBytes)]
-/// An agents chain records returned from a agent_activity_query
+/// An agent's status and chain records returned from a [ `get_agent_activity` ]
+/// query.
 pub struct AgentActivity {
-    /// Valid actions on this chain. `(sequence, action_hash)`.
+    /// Valid actions on this chain matching the filters passed to the query,
+    /// as a vector of `(sequence_index, action_hash)` tuples. **Note**:
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]:
```suggestion
    /// as a vector of `(action_sequence, action_hash)` tuples. **Note**:
```

File: crates/hdk/src/chain.rs (hunk 1 above)
Comment (pdaoust) [reply crates/hdk/src/chain.rs]: fixed in https://github.com/holochain/holochain/pull/5287/commits/0ed340e7931c6b3aced89c012dba816064fb5d25#diff-98df548c6583918717e436e47d25ba256793758ca99c9e43be13e1c0ed7803ecL13-R13

File: crates/holochain_zome_types/src/query.rs (hunk 3 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: sigghhhhhhhhhhhhhhhhhhh

**Review by jost-s — COMMENTED** [review]
I'll continue review on Monday.

File: crates/holochain_zome_types/src/query.rs [hunk 7]
```diff
@@ -105,42 +111,76 @@ pub struct LinkQuery {
...
 
-/// An agent's chain records, returned from an agent activity query.
+/// An agent's status and chain records returned from a `hdk::chain::get_agent_activity`
+/// query.
 #[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, SerializedBytes)]
 pub struct AgentActivity {
-    /// Valid actions on this chain. `(sequence, action_hash)`.
+    /// Valid actions on this chain matching the filters passed to the query,
+    /// as a vector of `(sequence_index, action_hash)` tuples. **Note**:
+    /// Warrants received from other sources are not reflected in this field;
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: I don't understand what this is supposed to mean. I think it's fine to emphasize that only valid actions are included, but I find the mentioning of warrants confusing.

File: crates/holochain_zome_types/src/query.rs [hunk 8]
```diff
@@ -105,42 +111,76 @@ pub struct LinkQuery {
...
+    /// it simply contains actions whose [ `RegisterAgentActivity` ] operations
+    /// are valid.
     pub valid_activity: Vec<(u32, ActionHash)>,
-    /// Rejected actions on this chain. `(sequence, action_hash)`.
+    /// Rejected actions on this chain matching the filters passed to the
+    /// query, as a vector of `(sequence_index, action_hash)` tuples.  **Note**:
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]:
```suggestion
    /// query, as a vector of `(action_sequence, action_hash)` tuples.  **Note**:
```

File: crates/holochain_zome_types/src/query.rs [hunk 9]
```diff
@@ -105,42 +111,76 @@ pub struct LinkQuery {
...
+    /// Warrants received from other sources are not reflected in this field;
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: Again, I don't know what this refers to. With the signature of `(u32, ActionHash)`, it's clear that this has got nothing to do with warrants.

File: crates/holochain_zome_types/src/query.rs [hunk 10]
```diff
@@ -105,42 +111,76 @@ pub struct LinkQuery {
...
-/// If there is more then one then there is a fork.
+/// The highest action sequence index for an agent's chain that has been
+/// _observed_, but not necessarily validated and integrated, by this
+/// authority. This struct is seen in the [ `AgentActivity` ] response from
+/// the `hdk::chain::get_agent_activity` query.
 ///
-/// This type is to prevent actions being hidden by
-/// withholding the previous action.
+/// This struct also includes the hash(es) of the action(s) at this sequence
+/// index. If there is more than one, then there is a fork.
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: I doubt that this is considering forks. In any case I wouldn't mention it here, because we're not supporting fork warrants yet, and there is only one highest observed action sequence, whether it's known to come from a fork or not.

File: crates/holochain_zome_types/src/query.rs [hunk 11]
```diff
@@ -105,42 +111,76 @@ pub struct LinkQuery {
...
+/// shouldn't be used as a dependency when constructing another action that
+/// depends on its validity. Instead, check that value of
+/// [ `AgentActivity::status` ] is [ `ChainStatus::Valid` ], an enum variant
+/// which will contain the highest sequence index and action hash for a locally
+/// validated action; and the [ `AgentActivity::warrants` ] field, which may
+/// contain warrants from other DHT authorities that have found the action to be
+/// invalid from the perspective of the DHT operations they've validated.
+
+// The information is tracked at the edge of holochain before
+// validation (but after drop checks).
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: Maybe it's just me, but this comment was before and still is unintelligible.

File: crates/holochain_zome_types/src/query.rs [hunk 12]
```diff
@@ -159,33 +201,60 @@ pub enum ChainStatus {
     /// This authority has no information on the chain.
     #[default]
     Empty,
-    /// The chain is valid as at this action sequence and action hash.
+    /// The chain is valid from the perspective of this authority, and the
+    /// highest integrated action is at the given sequence index and action
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]:
```suggestion
    /// highest integrated action is at the given action sequence and action
```

File: crates/holochain_zome_types/src/query.rs [hunk 13]
```diff
@@ -105,42 +111,76 @@ pub struct LinkQuery {
...
-/// An agent's chain records, returned from an agent activity query.
+/// An agent's status and chain records returned from a `hdk::chain::get_agent_activity`
+/// query.
 #[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize, SerializedBytes)]
 pub struct AgentActivity {
-    /// Valid actions on this chain. `(sequence, action_hash)`.
+    /// Valid actions on this chain matching the filters passed to the query,
+    /// as a vector of `(sequence_index, action_hash)` tuples. **Note**:
+    /// Warrants received from other sources are not reflected in this field;
+    /// it simply contains actions whose [ `RegisterAgentActivity` ] operations
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: In only notice this now, there shouldn't be a space between the bracket and the tick. Please review this throughout the changes.
```suggestion
    /// it simply contains actions whose [`RegisterAgentActivity`] operations
```

File: crates/holochain_zome_types/src/query.rs [hunk 14]
```diff
@@ -159,33 +201,60 @@ pub enum ChainStatus {
...
+    /// information is not reflected here but is instead found in the
+    //// [ `AgentActivity::warrants` ] field.
     Invalid(ChainHead),
 }
 
 #[derive(Clone, Debug, Hash, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
-/// The action at the head of the complete chain.
-/// This is as far as this authority can see a
-/// chain with no gaps.
+/// A pairing of a sequence index and its corresponding action hash in a chain.
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: Another general comment comment: Please keep comments above Rust tags like `#[derive`.

File: crates/holochain_zome_types/src/query.rs [hunk 15]
```diff
@@ -159,33 +201,60 @@ pub enum ChainStatus {
...
 }
 
 #[derive(Clone, Debug, Hash, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
-/// The chain has been forked by these two actions
+/// The chain has been forked by these two actions at this point. The ordering
+/// of the values in `first_action` and `second_action` is not guaranteed to be
+/// identical across peers; and, in cases of three or more actions (A, B, C)
+/// causing a fork at the same spot, the values are not guaranteed to be
+/// identical either (some authorities may report A and B, others may report C
+/// and A, and so on).
```
Comment (jost-s) [inline crates/holochain_zome_types/src/query.rs]: I don't know if this behaves as you describe, because we're not working on fork warrants yet.

**Review by jost-s — CHANGES_REQUESTED** [review]
Looks largely good to me.

Mainly formatting and style comments.

File: crates/holochain_zome_types/src/query.rs (hunk 11 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: heh, yeah. I downgraded it from a doc comment to a developers-only comment and still feel like it shouldn't be there. It's old history.

File: crates/holochain_zome_types/src/query.rs (hunk 13 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: oh good -- I saw that style being used elsewhere and it looked odd, but I kept with it for consistency. Happy to remove.

File: crates/holochain_zome_types/src/query.rs (hunk 15 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: Forks are still observed and reported, even if they're not warranted. Looking at the code, the ordering of the first and second is undefined -- the query is ordered by the seq but not the hash. And different authorities may have different forks.

File: crates/holochain_zome_types/src/query.rs (hunk 13 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: whooph... I went to do a global search/replace and this is _everywhere_ in the codebase (well okay, only 48 places). I'm going to do a follow-up PR to correct it all at once.

File: crates/hdk/src/chain.rs (hunk 5 above)
Comment (pdaoust) [reply crates/hdk/src/chain.rs]: I think it's valuable to be explicit about behaviour -- the lack of this has been a complaint about our documentation in the past.

File: crates/holochain_zome_types/src/query.rs (hunk 7 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: The issue is that invalid actions _may_ be included; `valid_actions` merely contains actions whose `RegisterAgentActivity` ops are valid.

File: crates/holochain_zome_types/src/query.rs (hunk 10 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: removing this line until fork detection is more stable, but for archaeological purposes I'll summarise the conversation Jost and I had on Mattermost: looking at the code, it does consider forks, but fork detection is unstable, so we don't want to promise any particular behaviour.

File: crates/holochain_zome_types/src/query.rs (hunk 14 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: another one of those cases where I'm following patterns I've seen elsewhere -- I'll fix docs comments that I've touched, then do the rest in another PR.

File: crates/holochain_zome_types/src/query.rs (hunk 7 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: updated the text: https://github.com/holochain/holochain/commit/5be0978d41a27834fcf733b8fcbc1b129f9dbaf2#diff-2778d2de66287213a6687439e1fe0c1fc2960db6db17a8a8a4750c747ae9a7cdL120-R127

File: crates/holochain_zome_types/src/query.rs (hunk 9 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: Much simplified: https://github.com/holochain/holochain/commit/5be0978d41a27834fcf733b8fcbc1b129f9dbaf2#diff-2778d2de66287213a6687439e1fe0c1fc2960db6db17a8a8a4750c747ae9a7cdL126-R131

File: crates/holochain_zome_types/src/query.rs (hunk 10 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: removed in https://github.com/holochain/holochain/commit/5be0978d41a27834fcf733b8fcbc1b129f9dbaf2#diff-2778d2de66287213a6687439e1fe0c1fc2960db6db17a8a8a4750c747ae9a7cdL166-R171

File: crates/holochain_zome_types/src/query.rs (hunk 11 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: removed in https://github.com/holochain/holochain/commit/5be0978d41a27834fcf733b8fcbc1b129f9dbaf2#diff-2778d2de66287213a6687439e1fe0c1fc2960db6db17a8a8a4750c747ae9a7cdL183-L185

File: crates/holochain_zome_types/src/query.rs (hunk 15 above)
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs]: Added caveats about unstable behaviour in https://github.com/holochain/holochain/commit/5be0978d41a27834fcf733b8fcbc1b129f9dbaf2#diff-2778d2de66287213a6687439e1fe0c1fc2960db6db17a8a8a4750c747ae9a7cdR217-R218 and https://github.com/holochain/holochain/commit/5be0978d41a27834fcf733b8fcbc1b129f9dbaf2#diff-2778d2de66287213a6687439e1fe0c1fc2960db6db17a8a8a4750c747ae9a7cdR248-R249

**Comment by pdaoust** [comment]
@jost-s I've made changes to the critical bits; please review and let me know if the text is better now. I've also corrected all the formatting inconsistencies in comments that I touched -- I'll follow up with another PR for parts of the codebase that I didn't touch.

File: crates/holochain_zome_types/src/query.rs [hunk 16]
```diff
@@ -108,86 +114,147 @@ pub struct LinkQuery {
...
-    /// Chain is invalid because of this action.
+    /// The chain is not forked, but is invalid from the given action sequence
+    /// and action hash forward, by virtue of this authority finding a
+    /// [`RegisterAgentActivity`] DHT operation for that action to be
+    /// invalid. There may be other types of operations for the chain's
+    /// actions which other authorities have found to be invalid; this
+    /// information is not reflected here but is instead found in the
+    //// [`AgentActivity::warrants`] field.
     Invalid(ChainHead),
 }
```
[the remark this answers is not in the document]
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs:225]: fixed, but not pushing until I get more feedback -- don't want to trigger too much CI.

(Partially fixed, that is -- a not-fully-qualified `[RegisterAgentActivity]` does not produce a build failure, so I'm not fixing that)

File: crates/holochain_zome_types/src/query.rs [hunk 17]
```diff
@@ -108,86 +114,147 @@ pub struct LinkQuery {
...
 pub struct HighestObserved {
     /// The highest sequence number observed.
     pub action_seq: u32,
-    /// Hashes of any actions claiming to be at this
-    /// action sequence.
+    /// Hashes of any actions claiming to be at this action sequence. Note that
+    /// this is a vector and may contain more than one hash in the case of a
+    /// chain fork.
     pub hash: Vec<ActionHash>,
 }
```
[the remark this answers is not in the document]
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs:186]: This PR is only about documentation, not about refactoring. (Although I do agree with you.)

[the remark this answers is not in the document]
Comment (pdaoust) [reply crates/holochain_zome_types/src/query.rs:186]: No thank you -- the entire HDK needs some love, and I'm sure it'll get addressed in a usability sweep.

**Review by jost-s — APPROVED** [review]
Yeah!
