### PR TITLE
Validate warrants

### LINKED ISSUE #5224: Issue a warrant when an invalid warrant is received
Warrants must be validated. If a warrant is invalid, a warrant should be issued against the author of the invalid warrant.

This should only happen once, so a warrant of an invalid warrant that itself fails validation should be disregarded.

AC:
- Create a new warrant variant `InvalidWarrantOp` with the invalid warrant op as a field
- Extend sys validation to validate warrants
- Issue a warrant if a warrant is invalid, but
- Invalid `InvalidWarrantOp`s should not result in a new warrant, only chain fork and invalid chain op warrants

### PR DESCRIPTION
**Pull request by ThetaSinner**
### Summary

Closes #5224

The general approach here is to try to fit in with what sys validation already does but warrants are a little different so here goes:
- The database query has been updated so that warrant `DhtOp`s are also fetched
- The dependency tracking has been updated to track warrant dependencies:
  - Initially, warrant dependencies are treated as unvalidated dependencies
  - In the unvalidated state, ops may be copied from the cache to the DHT database
  - Once a validation status is observed it is captured into the dependency tracking state
- When attempting to validate a warrant, we now wait until there is a validation status for the warranted op
- If the op passed validation then the warrant is treated as invalid

There is now a test for the happy path that should already have been here but was missing. A test has also been added that checks what happens when a warrant is issued of a valid op.

Things I'm leaving out of this PR because it's already too big:
- Updating the sys validation documentation to describe how warrants are validated
- Integration tests for warrants to check that the warrant validation logic works properly when app validation is also involved.
- I'm thinking it's best that we don't try to optimize only running one kind of validation and should remove the "validation type" from the warrant. If the op fails sys validation then it's not an optimization to only run sys validation and that'd be hard to do anyway because how would app validation know? If we have to run app validation then I think it would be a mistake to skip sys validation because it breaks the assumptions made by app validation about what has already been checked.
- Test that a warrant dependency that is already validated can be loaded and used to validate the warrant.
- Extract dependency fetching stream to its own function.

### TODO:
- [x] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

## Summary by CodeRabbit

- New Features
  - System validation now treats warrants as first-class dependencies and unifies Action+Warrant sources for consistent ordering and processing; warranted dependencies trigger re-validation when available.

- Bug Fixes / Improvements
  - Progress tracking for copied warrant dependencies added.
  - Copy-from-cache-to-DHT now reports whether an op was actually copied.

- Documentation
  - Changelog updated with an Unreleased entry for warrant validation.

- Tests
  - New feature-gated tests covering valid/invalid warrant scenarios (cached and network-fetched).

### CODE REVIEW

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 1]
```diff
@@ -159,48 +162,83 @@ pub async fn sys_validation_workflow(
...
-                Ok(Some((action, source))) => {
-                    let mut deps = current_validation_dependencies.lock().expect("poisoned");
-
-                    // If the source was local then that means some other fetch has put this action into the cache,
-                    // that's fine we'll just grab it here.
-                    if deps.insert(action, source) {
-                        1
-                    } else {
-                        0
+        .get_missing_dependencies();
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:168]: Some renaming around the `SysValDeps` struct to reflect changes in behavior

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 2]
```diff
@@ -159,48 +162,83 @@ pub async fn sys_validation_workflow(
...
+                                //      It would be more efficient to wait a bit before trying again.
+                                0
+                            }
+                            Err(err) => {
+                                tracing::error!(?err, "Error fetching missing dependency");
+                                0
+                            }
+                        }
+                    }
+                    ValidationDependencyType::Warranted(chain_op_type) => {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:202]: Add separate handling for fetching warrant dependencies because the integration with the `SysValDeps` needs to be treated a bit differently. See the call to `insert_pending_validation_warranted`

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 3]
```diff
@@ -215,10 +253,17 @@ pub async fn sys_validation_workflow(
         trigger_self.trigger(&"sys_validation_workflow");
     }
 
+    if outcome_summary.warrant_deps_copied > 0 {
+        // If any warrant dependencies were copied, the workflow could attempt validation for those
+        // right away, so trigger it again.
+        trigger_self.trigger(&"sys_validation_workflow");
+    }
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs]: Keep track of whether any warranted deps were copied from the cache to the DHT because that should immediately re-trigger the workflow to validate the newly inserted dependency

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 4]
```diff
@@ -414,43 +523,52 @@ async fn sys_validation_workflow_inner(
     Ok(summary)
 }
 
-async fn retrieve_actions(
+async fn retrieve_dependencies(
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:536]: More renaming to match updated usage

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 5]
```diff
@@ -783,11 +924,11 @@ async fn validate_warrant_op(
...
                 ..
             } => {
-                let action = {
+                let (action, validation_status) = {
                     let deps = validation_dependencies.lock().expect("poisoned");
-                    let action = deps
+                    let (action, validation_status) = deps
                         .get(action_hash)
-                        .and_then(|s| s.as_action())
+                        .and_then(|s| s.as_action_and_validation_status())
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:941]: Need the validation status for the warranted op before proceeding here. The warrant will be treated as "missing deps" until the dependency has a validation outcome. That will cause the sys validation workflow to keep running on its timer until the dependency is ready.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 6]
```diff
@@ -799,10 +940,36 @@ async fn validate_warrant_op(
...
+                    ValidationStatus::Valid => {
+                        // TODO block the warrant author
+                        return Err(SysValidationError::ValidationOutcome(
+                            ValidationOutcome::InvalidWarrant(
+                                Box::new(op.warrant().clone()),
+                                "Warranted op is valid".into(),
+                            ),
+                        ));
+                    }
+                    ValidationStatus::Abandoned => {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:967]: Can't really do much with this status... it should be implemented everywhere or removed

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 7]
```diff
@@ -799,10 +940,36 @@ async fn validate_warrant_op(
...
+                        //       no implementation of abandon yet.
+                        return Err(SysValidationError::WorkflowError(Box::new(
+                            WorkflowError::Other(Box::new(std::io::Error::other(
+                                "Warranted op is abandoned",
+                            ))),
+                        )));
+                    }
+                    ValidationStatus::Rejected => {
+                        // This is good, the warrant is valid because we also rejected the op
+                        // TODO block the author of the op
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:979]: Leaving blocking TODOs as a placeholder. This may not be the right place to actually implement the blocks but still want it tracked approximately.

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs [hunk 8]
```diff
@@ -313,6 +313,182 @@ async fn validate_op_with_wrong_sequence_number_rejected_and_not_forwarded_to_ap
     test_case.expect_app_validation_not_triggered().await;
 }
 
+#[cfg(feature = "unstable-warrants")]
+#[tokio::test(flavor = "multi_thread")]
+async fn validate_valid_warrant_with_cached_dependency() {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:320]: Happy path test where the warranted op has already been fetched into the cache database. It will have to be copied to the DHT and validated. The warrant will then be seen as valid.

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs [hunk 9]
```diff
@@ -313,6 +313,182 @@ async fn validate_op_with_wrong_sequence_number_rejected_and_not_forwarded_to_ap
...
+            Some(holochain_zome_types::prelude::ValidationStatus::Valid)
+        ),
+        "Warrant was not valid as expected, got: {:?}",
+        status
+    );
+}
+
+#[cfg(feature = "unstable-warrants")]
+#[tokio::test(flavor = "multi_thread")]
+async fn reject_invalid_warrant() {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:481]: Invalid warrant test. A valid op is put in the DHT and then a warrant is issued for it. Once the op is judged valid, the warrant is judged invalid and rejected.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 10]
```diff
@@ -80,23 +83,13 @@ impl ValidationDependencies {
         }
     }
 
-    pub fn get_mut(&mut self, hash: &ActionHash) -> Option<&mut ValidationDependencyState> {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs:83]: This wasn't used anywhere, removed. This is why it's really important to scope the visibility of everything down to a minimum because Clippy won't pick up that public types aren't used within the project and report it... because they might be used outside the project. Except this type is completely internal to sys validation... Mess!

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 11]
```diff
@@ -214,15 +380,55 @@ impl ValidationDependencyState {
...
+pub(super) enum ValidationDependencyValue {
+    Action(SignedActionHashed),
+    Warranted(WarrantedDep),
+}
+
+#[derive(Clone, Debug)]
+pub(super) enum WarrantedDep {
+    Pending(SignedActionHashed, ChainOpType),
+    Validated(SignedActionHashed, ValidationStatus),
+}
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs:435]: Note that warrant dependencies can be in two states. First, we discover the dependency and need to try to fetch it and ensure that it's in the DHT database. Then later the op can have a validation status that lets the warrant validation proceed.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs [hunk 12]
```diff
@@ -46,6 +50,30 @@ async fn get_ops_to_validate(
...
+            FROM DhtOp
+            JOIN Warrant ON DhtOp.action_hash = Warrant.hash
+
+            WHERE
+            DhtOp.when_integrated IS NULL
+            AND DhtOp.validation_status IS NULL
+            AND (
+                DhtOp.validation_stage IS NULL
+                OR DhtOp.validation_stage = 0
+            )
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs:78]: Sys validation was claiming to validate warrants but that can't have been tested because the database query was broken by the refactor to split warrants out of the action table... There were tests for issuing warrants but not validating them.

File: crates/holochain_state/src/mutations.rs [hunk 13]
```diff
@@ -1167,12 +1167,14 @@ pub fn remove_countersigning_session(
...
 /// nothing to be done.
+///
+/// Returns `true` if the op was copied, `false` if it already existed in the DHT database.
 pub async fn copy_cached_op_to_dht(
     dht: DbWrite<DbKindDht>,
     cache: DbRead<DbKindCache>,
     action_hash: ActionHash,
     chain_op_type: ChainOpType,
-) -> StateMutationResult<()> {
+) -> StateMutationResult<bool> {
```
Comment (ThetaSinner) [inline crates/holochain_state/src/mutations.rs:1177]: Minor modification. As was predicted on the PR that added this function, more information about what it did is needed. Tracking not just whether everything worked, but whether this function did work. If it did, it's acceptable to re-trigger sys validation to validated the moved dependency.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 14]
```diff
@@ -414,43 +470,119 @@ async fn sys_validation_workflow_inner(
...
+    for (action_hash, op_type) in warrant_deps {
+        match copy_cached_op_to_dht(
+            workspace.dht_db.clone(),
+            workspace.cache.clone().into(),
+            action_hash.clone(),
+            op_type,
+        )
+        .await
+        {
+            Ok(copied) => {
```
Comment (veeso) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs]:
```suggestion
            Ok(true) => {
                *warrant_deps_copied += 1;
            }
            Ok(false) => {}
```

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 15]
```diff
@@ -159,48 +162,83 @@ pub async fn sys_validation_workflow(
...
-                    // If the source was local then that means some other fetch has put this action into the cache,
-                    // that's fine we'll just grab it here.
-                    if deps.insert(action, source) {
-                        1
-                    } else {
-                        0
+        .get_missing_dependencies();
+    let num_fetched: usize =
+        futures::stream::iter(missing_dependencies.into_iter().map(|(hash, dep_type)| {
+            let network_cascade = network_cascade.clone();
```
Comment (veeso) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:171]: I think this future could be moved into a function

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 16]
```diff
@@ -123,8 +116,34 @@ impl ValidationDependencies {
...
+    pub fn insert_action(&mut self, action: SignedActionHashed, source: CascadeSource) -> bool {
+        let hash = action.as_hash();
+
+        // Note that `has` is checking that the dependency is actually set, not just that we have the key!
+        if self.has(hash) {
+            tracing::warn!(hash = ?hash, "Attempted to insert a dependency that was already present, this is not expected");
+            return false;
+        }
+
+        self.retained_deps.insert(hash.clone());
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: The call to `self.has()` is already doing this insert so I think it's redundant as it stands. Maybe that redundancy is welcome in case `self.has()` changes under the hood at some point?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 17]
```diff
@@ -136,14 +155,31 @@ impl ValidationDependencies {
         self.retained_deps.insert(hash.clone());
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Same redundancy here.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 18]
```diff
@@ -202,10 +315,63 @@ impl ValidationDependencyState {
         }
     }
 
+    pub(super) fn set_pending_validation_warranted(
+        &mut self,
+        action: SignedActionHashed,
+        op_type: ChainOpType,
+    ) {
+        if self.dependency_type == ValidationDependencyType::Action {
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Can we check for `!= ValidationDependencyValue::Warranted` here instead to guard against the enum potentially being extended in the future?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 19]
```diff
@@ -202,10 +315,63 @@ impl ValidationDependencyState {
...
+                tracing::warn!("Attempted to set a record on a dependency that already has a value, this is a bug")
+            }
+        }
+    }
+
+    pub(super) fn set_validation_status_for_warranted(
+        &mut self,
+        validation_status: ValidationStatus,
+    ) {
+        if self.dependency_type == ValidationDependencyType::Action {
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Same here, checking for `!= ValidationDependencyValue::Warranted` rather?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 20]
```diff
@@ -202,10 +315,63 @@ impl ValidationDependencyState {
...
+            tracing::warn!("Attempted to set an action on a dependency that is not of type Action, this is a bug");
+            return;
+        }
+
+        match self.dependency.take() {
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Why are we using `.take()` here? It seems to me like there are cases other than `None` that would be covered by the second match arm below that only logs a warning but in that case the existing value would still be overwritten by `None`. Is this intentional?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 21]
```diff
@@ -169,30 +241,71 @@ impl ValidationDependencies {
...
         Self {
-            dependency: Some(ValidationDependency { dep, fetched_from }),
+            dependency_type,
+            dependency: None,
         }
     }
 
-    pub fn set_dep(&mut self, dep: SignedActionHashed) {
+    pub(super) fn set_action_dep(&mut self, action: SignedActionHashed) {
+        if let ValidationDependencyType::Warranted(_) = self.dependency_type {
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Analogously to my comments below, I think I'd rather make a comparison `!= ValidationDependencyType::Action` here.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 22]
```diff
@@ -202,10 +315,63 @@ impl ValidationDependencyState {
         }
     }
 
+    pub(super) fn set_pending_validation_warranted(
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs:319]: I think docstrings would be nice for these new methods.

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 8 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:320]: This would make for a great comment above the test!

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 9 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:481]: Equally here, please add this as a test comment.

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs [hunk 23]
```diff
@@ -313,6 +313,182 @@ async fn validate_op_with_wrong_sequence_number_rejected_and_not_forwarded_to_ap
...
+
+    test_case
+        .save_op_to_db(
+            test_case.dht_db_handle(),
+            DhtOp::WarrantOp(warrant_op.into()),
+        )
+        .await
+        .unwrap();
+
+    // Discover the warrant op in the cache and move it to the DHT
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs]:
```suggestion
    // Discover the warranted op in the cache and copy it to the DHT
```

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 8 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:320]: As there is a different handling for fetching warrant dependencies, I request a test showing that the dependency is fetched if not yet present in the stores.

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs [hunk 24]
```diff
@@ -464,4 +669,36 @@ impl TestCase {
         .err()
         .is_some());
     }
+
+    #[cfg(feature = "unstable-warrants")]
+    fn get_warrant_outcome(
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs]:
```suggestion
    fn get_warrant_validation_outcome(
```

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 25]
```diff
@@ -123,8 +116,34 @@ impl ValidationDependencies {
             .collect()
     }
 
+    /// Insert an action which was found after this set of dependencies was created.
+    pub fn insert_action(&mut self, action: SignedActionHashed, source: CascadeSource) -> bool {
+        let hash = action.as_hash();
+
+        // Note that `has` is checking that the dependency is actually set, not just that we have the key!
+        if self.has(hash) {
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: `has` as a name for a function that manipulates state is misleading.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 12 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs:78]: Yep!

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs [hunk 26]
```diff
@@ -68,8 +98,8 @@ async fn get_ops_to_validate(
     sql.push_str(
         "
         ORDER BY
-        DhtOp.num_validation_attempts ASC,
-        DhtOp.op_order ASC
+        t.num_validation_attempts ASC,
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs]: Please update the doc comment for this function regarding the ordering.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs [hunk 27]
```diff
@@ -58,6 +86,8 @@ async fn get_ops_to_validate(
                 DhtOp.validation_stage = 1
                 OR DhtOp.validation_stage = 2
             )
+
+            ) t
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs]: `op` instead of `t`? Or what does `t` stand for?
```suggestion
            ) op
```

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs [hunk 28]
```diff
@@ -23,12 +23,16 @@ async fn get_ops_to_validate(
     system: bool,
 ) -> WorkflowResult<Vec<DhtOpHashed>> {
     let mut sql = "
+        SELECT * FROM (
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs:30]: I'm requesting a unit test to ensure that warrant ops are included.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 29]
```diff
@@ -215,10 +253,17 @@ pub async fn sys_validation_workflow(
         trigger_self.trigger(&"sys_validation_workflow");
     }
 
+    if outcome_summary.warrant_deps_copied > 0 {
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs]: Instead of triggering twice, how about combining it with the previous trigger?
```suggestion
    if num_fetched > 0 || outcome_summary.warrant_deps_copied > 0 {
```

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 25 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: This came up on the original PR too but the point of the sate modification isn't to modify the queried data structure, it is to track the access to that data structure to work out which keys were accessed and which weren't. It's part of the maintenance logic for the data structure. The caller doesn't really need to worry about that and the purpose of the function is to return a "has key" boolean

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 16 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: No you're right, removed

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 28 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs:30]: I will add unit tests if you think that's necessary but I added this because the unit tests added in `crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs` didn't pick up warrants until I made this change. If warrants weren't being picked up by this query then those unit tests would not pass. 

I think that's a valid testing approach because it's testing the workflow and there's no full conductor running where something that we don't expect might be happening other than warrants getting fetched from the database during workflow runs.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 27 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs]: `t` stands for table, it's a needed to sort and limit the result of the unioned selects. I've renamed it to `union_table`

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 8 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:320]: Added new test `validate_valid_warrant_with_fetched_dependency`

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 14 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: I don't like that you lose the variable name like this so I did it slightly differently than the suggestion but eliminated the nested `if` as requested

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 15 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs:171]: Added this to the list of things that don't fit in this PR that I'll do as a follow up. I agree, but I already think this diff is hard enough to follow

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 20 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Because the inner action of the old value needs to be borrowed while also mutating the top level of it. The compiler rightly doesn't let you do that. 

There shouldn't be cases where this takes but is unable to modify, that is supposed to be prevented by the guard condition at the start of the function

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 22 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs:319]: They are private to the module but okay

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 26 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs]: Good spot. This function is actually called by both `get_ops_to_app_validate` and `get_ops_to_sys_validate`. Updated the doc comments on both to include the sorting by validation attempts.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 29 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: This doesn't actually trigger twice because the trigger queue only has space for one trigger so it's really more like a "triggered" boolean. I think this is clearer split into two and commented separately but I can change it if it's too unclear.

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 8 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:320]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 9 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs:481]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 14 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 15 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs:171]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 18 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 19 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 21 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 22 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs:319]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 23 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs (hunk 24 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/unit_tests.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 26 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 27 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs]: https://github.com/holochain/holochain/pull/5249/commits/9801bda0488c75727acee3e09527cb747eeaf3d9

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 20 above)
Comment (matthme) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: > that is supposed to be prevented by the guard condition at the start of the function

That only guards against not being `ValidationDependencyValue::Warranted` but the match arm of `self.dependency.take()` is more specifically checking for
```
ValidationDependencyValue::Warranted(WarrantedDep::Pending(action, _))
```
so the catch `_` arm includes `ValidationDependencyValue::Warranted(WarrantedDep::Validated(_))` I think.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs (hunk 28 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_query.rs:30]: The argument is that this function might be used in different places, but right now it isn't. I'm fine with not adding a test.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 29 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: If it's just one trigger in effect anyway, I find it clearer to reflect that in the condition, because you don't need to know the internal of the trigger then.

Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: https://github.com/holochain/holochain/pull/5249/commits/00089869473c8c7a97e7dad7725e4bd2ad07f974

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 20 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: That's true. I think quite a bit would have to go wrong to hit that though and it will print a warning. Worst case scenario is that the data has to be fetched from the database again but if the state logic is broken then things aren't going to progress either way.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 30]
```diff
@@ -159,48 +162,86 @@ pub async fn sys_validation_workflow(
...
+                                0
+                            }
+                            Err(err) => {
+                                tracing::error!(?err, "Error fetching missing dependency");
+                                0
+                            }
+                        }
+                    }
+                    ValidationDependencyType::Warranted(chain_op_type) => {
+                        println!("Fetching warranted dependency from network: {}", hash);
```
Comment (matthme) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs]: Are these `println!`s intended to be kept (or converted to a tracing instead)? There's one a few lines below as well.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs (hunk 20 above)
Comment (matthme) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: Okay, fair enough :+1:

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 30 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: Should have been removed, they were for debugging. Thanks for picking that up.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs [hunk 31]
```diff
@@ -169,43 +237,143 @@ impl ValidationDependencies {
...
+                        validation_status,
+                    )),
+                    fetched_from,
+                });
+            }
+            _ => {
+                tracing::warn!("Attempted to set a status for a dependency that is not pending validation, this is a bug")
             }
         }
     }
```
[the remark this answers is not in the document]
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validation_deps.rs]: If you insist
