### PR TITLE
fix: return error from must_get_valid_record when record is invalid

### LINKED ISSUE #4669: [Bug] `must_get_valid_record` should short-circuit when an invalid op is found
`must_get_valid_record` currently short-circuits `validate` and `init` with `UnresolvedDependencies` for all failures, including when a warrant is found. This causes validation to be retried, yet even a single warrant should definitively and deterministically mark it as invalid so it shouldn't be retried.

There are cases where dependent data will have to be invalidated after an upstream warrant emerges post-validation, or de-invalidate after an upstream warrant is cancelled. But this is something that'll have to be handled by other means, which is outside the scope of this issue.

I know there are a lot of other issues with validation, so this should be deferred until a proper sweep is done.

### PR DESCRIPTION
**Pull request by jost-s**
### Summary

resolves #4669 

### TODO:
- [x] CHANGELOGs updated with appropriate info
- [x] All code changes are reflected in docs, including module-level docs

## Summary by CodeRabbit

* **Bug Fixes**
  * Invalid records now return a clear "Invalid" validation error instead of a misleading unresolved-dependencies error, improving observed validation behavior.

* **Tests**
  * Added tests confirming validation callbacks reject when depending on invalid records; note: duplicated test instances included.

* **Documentation**
  * Changelog updated to reflect the revised error handling and validation outcomes.

### CODE REVIEW

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs [hunk 1]
```diff
@@ -342,6 +353,85 @@ async fn validation_callback_awaiting_deps_agent_activity() {
     assert_matches!(outcome, Outcome::Accepted);
 }
 
+// An op under validation that depends on an invalid op should be rejected.
+#[tokio::test(flavor = "multi_thread")]
+async fn validation_callback_rejects_op_depending_on_invalid_op() {
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:353]: This tests that an op that depends on an invalid op with a `must_get_valid_record` is also rejected by app validation.

File: crates/holochain/src/core/ribosome/host_fn/must_get_valid_record.rs [hunk 2]
```diff
@@ -117,3 +131,87 @@ pub fn must_get_valid_record(
...
+    use holochain_timestamp::Timestamp;
+    use holochain_types::dht_op::{ChainOp, DhtOp, DhtOpHashed};
+    use holochain_wasm_test_utils::TestWasm;
+    use holochain_wasmer_host::prelude::*;
+    use holochain_zome_types::validate::ValidationStatus;
+
+    // This test ensures the ValidationStatus::Rejected arm is hit and returns a
+    // HostShortCircuit carrying ValidateCallbackResult::Invalid with the expected message.
+    #[tokio::test(flavor = "multi_thread")]
+    async fn must_get_valid_record_short_circuit_when_invalid_record_found() {
```
Comment (jost-s) [inline crates/holochain/src/core/ribosome/host_fn/must_get_valid_record.rs:157]: This tests that `must_get_valid_record` returns an `ValidateCallbackResult::Invalid` when an invalid record is found.

File: crates/holochain/src/core/ribosome/host_fn/must_get_valid_record.rs [hunk 3]
```diff
@@ -60,6 +60,22 @@ pub fn must_get_valid_record(
                     .map_err(|cascade_error| -> RuntimeError {
                         wasm_error!(WasmErrorInner::Host(cascade_error.to_string())).into()
                     })? {
+                    // Only short-circuit as Invalid when running inside the Validate host context.
+                    Some(RecordDetails {
+                        validation_status: ValidationStatus::Rejected,
+                        ..
+                    }) if matches!((call_context).host_context, HostContext::Validate(_)) => {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/ribosome/host_fn/must_get_valid_record.rs:67]: Nice touch to ensure this only happens in validation

Comment (ThetaSinner) [inline crates/holochain/src/core/ribosome/host_fn/must_get_valid_record.rs:67]: Nice touch to ensure that this only happens in validation, to avoid mess with the error if this is called elsewhere.

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs [hunk 4]
```diff
@@ -342,6 +348,83 @@ async fn validation_callback_awaiting_deps_agent_activity() {
...
+    let outcome = run_validation_callback(
+        invocation.clone(),
+        &ribosome,
+        workspace.clone(),
+        network.clone(),
+        false,
+    )
+    .await
+    .unwrap();
+    assert_matches!(outcome, Outcome::Rejected(reason) if reason == "Found a record, but it is invalid");
```
Comment (matthme) [inline crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:425]: I'm noticing here that the error message is a bit unspecific when looking at it at the level of app validation. From the error `Found a record, but it is invalid` it's not really clear that it's a `must_get_valid_record()` that didn't return a record nor for which action hash. I'm not sure where these app validation errors are further being used so it might not be too much of a problem. It's probably also not an error that would normally occur in tryorama tests (because no invalid records would exist) where precise feedback is valuable at development time to understand potential application logic errors.

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs [hunk 5]
```diff
@@ -342,6 +348,83 @@ async fn validation_callback_awaiting_deps_agent_activity() {
...
+    let network = Arc::new(MockHolochainP2pDnaT::new());
+
+    // Insert invalid Create op into the cache db.
+    test_space.space.cache_db.test_write(move |txn| {
+        insert_op_cache(txn, &create_action_op).unwrap();
+        set_validation_status(txn, &create_action_op.hash, ValidationStatus::Rejected).unwrap();
+        set_when_integrated(txn, &create_action_op.hash, Timestamp::now()).unwrap();
+    });
+
+    // App validation should reject the Delete op because the Create it deletes is invalid.
```
Comment (matthme) [inline crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs]:
```suggestion
    // App validation should reject the CreateLink op because the record at the base address of the link is invalid.
```

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs (hunk 4 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:425]: I think at the app validation level, it will be a `WasmError`, so it should contain the file name and line number. It would be then something like
```
let dependent_record = must_get_valid_record(...)?;
```
with the corresponding line number and the error message saying "Found a record, but it is invalid". Do you think something else should be printed?

Comment (matthme) [reply crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:425]: You're right, the line number would be returned as well. In that case I think it's sufficient as it is.

**Review by matthme — APPROVED** [review]
