### PR TITLE
fix(app-validation-wf): remove ops to filter when multiple ops missing same hash 0.3

### LINKED ISSUE #3660: [BUG] Holochain v0.3.0-beta-dev.46 and later fail to reach consistency in app validation
**Describe the bug**

Some sweettests of normal scaffolded apps fail with holochain v0.3.0-beta-dev.46, with awaiting consistency errors, even when waiting for 60 seconds.

This is the logs I get:

```
❯ RUST_LOG=holochain::core::workflow=info DNA_PATH=../../../workdir/posts_test.dna cargo nextest run -j 1 --cargo-profile release
+ command cargo nextest run -j 1 --cargo-profile release
    Finished release [optimized] target(s) in 0.17s
    Starting 17 tests across 10 binaries (run ID: 4c26be29-5ca0-402f-b803-c3795de061c5, nextest profile: default)
        PASS [   2.941s] posts::all_posts create_a_post_and_get_all_posts
        PASS [   2.918s] posts::all_posts_entry_hash create_a_post_and_get_all_posts_entry_hash
        SLOW [> 60.000s] posts::certificate create_and_read_certificate
        FAIL [  61.961s] posts::certificate create_and_read_certificate

--- STDOUT:              posts::certificate create_and_read_certificate ---

running 1 test
Fixturator seed: 11264340770772231905
test create_and_read_certificate has been running for over 60 seconds
test create_and_read_certificate ... FAILED

failures:

failures:
    create_and_read_certificate

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 61.92s


--- STDERR:              posts::certificate create_and_read_certificate ---
2024-04-17T16:33:09.509657Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 7 ops
2024-04-17T16:33:09.511636Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 7/7 ops
2024-04-17T16:33:09.527406Z  INFO test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAkpDkOgh22lF3kHWUuvzqA6cYnkRkZ1_03kwtDTcjx4X7ULMn9)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 7 ops
2024-04-17T16:33:09.529258Z  INFO test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAkpDkOgh22lF3kHWUuvzqA6cYnkRkZ1_03kwtDTcjx4X7ULMn9)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 7/7 ops
2024-04-17T16:33:10.264770Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 17 ops
2024-04-17T16:33:10.269998Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 17/17 ops
2024-04-17T16:33:10.286106Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:51: publishing 9 ops
2024-04-17T16:33:10.288538Z  INFO test{scope="0.J5BXo"}:managed task{scope="0.J5BXo"}:publish_dht_ops_workflow{agent=AgentPubKey(uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w)}: holochain::core::workflow::publish_dht_ops_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/publish_dht_ops_workflow.rs:85: published 9/9 ops
2024-04-17T16:33:10.541199Z  WARN test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:app_validation_workflow{dna_hash=DnaHash(uhC0kJJ_Hzx2_dpQHwbNMFgXob27L27xKRXKv2R0yahK1Dg4fhcs-)}:write_async:spawn_blocking:execute_in_exclusive_rw_txn: holochain::core::workflow::app_validation_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/app_validation_workflow.rs:202: msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCkkQhGEMbi5mB5yJRsx3Gj3zcfdlEG0_WMUS8koZvHk1rrTZDM1)])
2024-04-17T16:33:10.579047Z  WARN test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:app_validation_workflow{dna_hash=DnaHash(uhC0kJJ_Hzx2_dpQHwbNMFgXob27L27xKRXKv2R0yahK1Dg4fhcs-)}:write_async:spawn_blocking:execute_in_exclusive_rw_txn: holochain::core::workflow::app_validation_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/app_validation_workflow.rs:202: msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCkkrF7vOBQ_Fv3-IY-nhKY0G0Ne-MOKuovxBqde1jlq_XO4P6MC)])
2024-04-17T16:33:10.579080Z  WARN test{scope="1.z-Unu"}:managed task{scope="1.z-Unu"}:app_validation_workflow{dna_hash=DnaHash(uhC0kJJ_Hzx2_dpQHwbNMFgXob27L27xKRXKv2R0yahK1Dg4fhcs-)}:write_async:spawn_blocking:execute_in_exclusive_rw_txn: holochain::core::workflow::app_validation_workflow: /tmp/posts-open-dev/posts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.3.0-beta-dev.46/src/core/workflow/app_validation_workflow.rs:202: msg="DhtOp has failed app validation" outcome=AwaitingDeps([AnyDhtHash(uhCkkrF7vOBQ_Fv3-IY-nhKY0G0Ne-MOKuovxBqde1jlq_XO4P6MC)])
FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        Timed out waiting for consistency: Consistency not achieved after 60s. Expected 40 ops, but only 38 integrated. Unintegrated ops:

        author                                                 seq  op_type (action_type)
        uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  10  StoreRecord (CreateLink)
        uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  11  StoreRecord (CreateLink)

        IntegrationStateDump { validation_limbo: 2, integration_limbo: 0, integrated: 38 },
    ),
    location: Location {
        file: "zomes/coordinator/posts/tests/certificate.rs",
        line: 68,
        col: 10,
    },
    can_unwind: true,
    force_no_backtrace: false,
}
thread 'create_and_read_certificate' panicked at zomes/coordinator/posts/tests/certificate.rs:68:10:
Timed out waiting for consistency: Consistency not achieved after 60s. Expected 40 ops, but only 38 integrated. Unintegrated ops:

author                                                 seq  op_type (action_type)
uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  10  StoreRecord (CreateLink)
uhCAk55MP1QP5qYUqq1E_DjFta-wlk5gldK5P-C54QEY7jwfnMP0w  11  StoreRecord (CreateLink)

IntegrationStateDump { validation_limbo: 2, integration_limbo: 0, integrated: 38 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure
        PASS [   1.943s] posts::certificate create_certificate_test
------------
     Summary [  69.763s] 4/17 tests run: 3 passed, 1 failed, 0 skipped
        FAIL [  61.961s] posts::certificate create_and_read_certificate
error: test run failed

```

**Expected behavior**

Sweettest works well.

### PR DESCRIPTION
**Pull request by jost-s**
### Summary
Fix bug where ops were stuck in app validation when multiple ops were requiring the same action or entry hash. Such ops were erroneously filtered out from validation for being marked as ops awaiting hashes and not unmarked as awaiting once the hashes had arrived.

`ValidationDependencies` was simplified too. Previously two separate hash maps were tracking hashes to be fetched and ops associated with these hashes. This is combined now and more filtering logic encapsulated in there. Tests added.

fixes #3660 

### TODO:
- [x] CHANGELOGs updated with appropriate info

### CODE REVIEW

File: crates/holochain/src/core/workflow/app_validation_workflow.rs [hunk 1]
```diff
@@ -650,58 +646,42 @@ async fn run_validation_callback(
...
+                "Op validation returned unresolved dependencies -  AgentActivity"
+            );
             // fetch all missing hashes in the background without awaiting them
             let cascade_workspace = workspace.clone();
             let cascade =
                 CascadeImpl::from_workspace_and_network(&cascade_workspace, network.clone());
 
-            // add hashes missing to validate an op to hash map
-            hashes.iter().for_each(|hash| {
-                validation_dependencies
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow.rs:660]: ops were added to awaited validation deps...

File: crates/holochain/src/core/workflow/app_validation_workflow.rs [hunk 2]
```diff
@@ -650,58 +646,42 @@ async fn run_validation_callback(
...
-
-            // build a collection of futures to fetch the individual missing
-            // hashes
-            let validation_deps = validation_dependencies.clone();
-            let dht_op_hash = dht_op_hash.clone();
-            let fetches = hashes
-                .clone()
-                .into_iter()
-                .filter(move |hash| {
-                    // keep track of which dependencies are being fetched to
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow.rs:673]: ... but may have been filtered out in case the hash was already being fetched...

File: crates/holochain/src/core/workflow/app_validation_workflow.rs [hunk 3]
```diff
@@ -650,58 +646,42 @@ async fn run_validation_callback(
...
-                        // or an error occurred along the way.
-                        // In case of an error the hash is still removed from
-                        // the collection so that it will be tried again to be
-                        // fetched in the subsequent workflow run.
-                        validation_dependencies.lock().remove_missing_hash(&hash);
-                        // Secondly remove the just fetched hash from the set
-                        // of missing hashes for the op
-                        validation_dependencies
-                            .lock()
-                            .remove_hash_missing_for_op(dht_op_hash, &hash);
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow.rs:702]: ... and therefore never removed from the list of ops missing hashes, which leads to the filtering out above.

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 4]
```diff
@@ -0,0 +1,289 @@
...
+
+use holo_hash::{AnyDhtHash, DhtOpHash};
+use holochain_types::dht_op::DhtOpHashed;
+
+/// In-memory struct to keep track of missing DHT hashes, which DhtOp depends on them
+/// and when they were started being fetched.
+pub struct ValidationDependencies {
+    /// Missing hashes that are being fetched, along with a set of DhtOps that depend
+    /// on the hash and the last Instant a fetch was attempted.
+    missing_hashes: HashMap<AnyDhtHash, (HashSet<DhtOpHash>, Instant)>,
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:14]: `missing_hashes` was hash map of missing hashes with the instant they were first fetched
`hashes_missing_for_op` was a hash map of op hash with the corresponding dht hashes to fetch

=> combined into `missing_hashes`, a hash map of the missing dht hash with the ops that depend on it and the instant it was first fetched

File: crates/holochain/src/core/workflow/app_validation_workflow.rs [hunk 5]
```diff
@@ -650,58 +646,42 @@ async fn run_validation_callback(
...
             // fetch all missing hashes in the background without awaiting them
             let cascade_workspace = workspace.clone();
             let cascade =
                 CascadeImpl::from_workspace_and_network(&cascade_workspace, network.clone());
 
-            // add hashes missing to validate an op to hash map
-            hashes.iter().for_each(|hash| {
-                validation_dependencies
-                    .lock()
-                    .insert_hash_missing_for_op(dht_op_hash.clone(), hash.clone());
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow.rs:662]: ops were added to awaited validation deps...

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 6]
```diff
@@ -0,0 +1,288 @@
+use std::{
+    collections::{hash_map::Entry, HashMap, HashSet},
+    time::{Duration, Instant},
+};
+
+use holo_hash::{AnyDhtHash, DhtOpHash};
+use holochain_types::dht_op::DhtOpHashed;
+
+/// In-memory struct to keep track of missing DHT hashes, which DhtOp depends on them
+/// and when they were started being fetched.
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:10]:
```suggestion
/// and when the fetches for them were most recently tried.
```

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 4 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:14]: The structure looks good but it is a more complex type. I'd be tempted to introduce a type to wrap the `(HashSet<DhtOpHash>, Instant)` but let's not mess with it as part of this PR :)

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 7]
```diff
@@ -0,0 +1,288 @@
...
+impl ValidationDependencies {
+    const FETCH_TIMEOUT: Duration = Duration::from_secs(60);
+
+    pub fn new() -> Self {
+        Self {
+            missing_hashes: HashMap::new(),
+        }
+    }
+
+    // returns true if this is a new missing hash
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:32]:
```suggestion
    /// returns true if this is a new missing hash
```

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 8]
```diff
@@ -0,0 +1,288 @@
...
+
+    pub fn remove_missing_hash(&mut self, hash: &AnyDhtHash) {
+        self.missing_hashes.remove(hash);
+    }
+
+    pub fn get_missing_hashes(&self) -> &HashMap<AnyDhtHash, (HashSet<DhtOpHash>, Instant)> {
+        &self.missing_hashes
+    }
+
+    // filter out hashes that are known to be missing
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:57]:
```suggestion
    /// filter out hashes that are known to be missing
```

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 9]
```diff
@@ -0,0 +1,288 @@
...
+
+    pub fn new() -> Self {
+        Self {
+            missing_hashes: HashMap::new(),
+        }
+    }
+
+    // returns true if this is a new missing hash
+    pub fn insert_missing_hash_for_op(&mut self, hash: AnyDhtHash, dht_op_hash: DhtOpHash) -> bool {
+        if let Entry::Vacant(entry) = self.missing_hashes.entry(hash.clone()) {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:34]: Prefer `match` on entry because that avoids having to call `.entry` twice?

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 10]
```diff
@@ -0,0 +1,288 @@
...
+            false
+        }
+    }
+
+    pub fn remove_missing_hash(&mut self, hash: &AnyDhtHash) {
+        self.missing_hashes.remove(hash);
+    }
+
+    pub fn get_missing_hashes(&self) -> &HashMap<AnyDhtHash, (HashSet<DhtOpHash>, Instant)> {
+        &self.missing_hashes
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:54]: Gives up internal state, what is this used for that shouldn't be a function on this type?

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 11]
```diff
@@ -0,0 +1,288 @@
...
+    }
+
+    // filter out hashes that are known to be missing
+    pub fn filter_missing_hashes_to_fetch_for_op(
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:58]: I'm finding this confusing but I think it's just naming. This is really a batch insert that returns the hashes that weren't yet being tracked. Could it maybe be named something like `insert_missing_deps_for_op` and have a doc comment to that effect?

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 12]
```diff
@@ -0,0 +1,288 @@
...
+    pub fn fetch_missing_hashes_timed_out(&self) -> bool {
+        if self.missing_hashes.is_empty() {
+            return false;
+        }
+        self.missing_hashes
+            .iter()
+            .all(|(_, (_, instant))| instant.elapsed() > Self::FETCH_TIMEOUT)
+    }
+
+    // filter out dht_ops that have missing dependencies
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:84]:
```suggestion
    /// filter out dht_ops that have missing dependencies
```

File: crates/holochain/src/core/workflow/app_validation_workflow.rs [hunk 13]
```diff
@@ -655,58 +651,42 @@ async fn run_validation_callback(
...
                     }
-                });
+                    // Dependency has been fetched and added to the cache
+                    // or an error occurred along the way.
+                    // In case of an error the hash is still removed from
+                    // the collection so that it will be tried again to be
+                    // fetched in the subsequent workflow run.
+                    validation_dependencies.lock().remove_missing_hash(&hash);
+                    // Secondly remove the just fetched hash from the set
+                    // of missing hashes for the op
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow.rs:687]: Comment no longer required because it's now folded into one data structure?

```suggestion
```

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs [hunk 14]
```diff
@@ -730,28 +769,15 @@ async fn hashes_missing_for_op_are_updated_before_and_after_fetching_deps() {
...
-            .hashes_missing_for_op
-            .get(&delete_dht_op_hash)
-            .unwrap()
-            .clone()
-            .into_iter()
-            .collect::<Vec<AnyDhtHash>>(),
-        vec![create_action_signed_hashed.as_hash().clone().into()]
-    );
+    // await while missing record is being fetched in background task
+    tokio::time::sleep(Duration::from_millis(10)).await;
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:773]: Any way to assert when this has happened or retry the check below? Sleeps are an easy way to get flaky tests when the CI environment slows down :/

**Review by ThetaSinner — COMMENTED** [review]
Great find, this fix description maps really well to the bug report and the logic of the validation deps seems solid now!

I have a few comments but nothing major :)

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs (hunk 14 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:773]: Ah, yeah, that's better. I'll take care of that.

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 4 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:14]: I was tempted to do that and didn't in the end. I'll do it with your encouragement. =)

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 10 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:54]: That was a perhaps lazy fix to tests accessing the internal state which was possible while this struct was still inside of the app validation workflow module. Is it preferable to change the field's scope to `pub(super)` or something like that?

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 9 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:34]: This is verbatim what clippy told me to use instead of some `.entry().or_insert()` construct. I prefer the match too. I'll tell clippy.

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 11 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:58]: Done and simplified

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 10 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:54]: Oh it's fair enough for testing but then maybe put it behind a `#[cfg(test)]`. I was wondering if that's the only place it was used from

**Comment by ThetaSinner** [comment]
Is this ready for re-review?

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs (hunk 14 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs]: Done for all tests in the module

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 10 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs]: Done

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs (hunk 9 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs]: Done

**Comment by jost-s** [comment]
> Is this ready for re-review?

Now it is.

File: crates/holochain/tests/regression/must_get_agent_activity_saturation.rs [hunk 15]
```diff
@@ -3,15 +3,15 @@ use holochain::sweettest::{SweetConductorBatch, SweetConductorConfig, SweetDnaFi
...
 use holochain_zome_types::prelude::Record;
 use rand::{thread_rng, Rng};
-use std::time::Duration;
 
 // Intended to keep https://github.com/holochain/holochain/issues/3028 fixed.
 // ensure that multiple `must_get_agent_activity` calls do not oversaturate the
 // fetch pool and bring gossip to a halt
 #[tokio::test(flavor = "multi_thread")]
 #[cfg(feature = "slow_tests")]
-#[ignore = "temporarily while working on app validation refactor; to be reinstated along the refactor"]
```
Comment (jost-s) [inline crates/holochain/tests/regression/must_get_agent_activity_saturation.rs:13]: test reinstated

File: crates/holochain_trace/src/lib.rs [hunk 16]
```diff
@@ -330,7 +330,10 @@ where
 {
     let filter = standard_filter()?;
 
-    println!("Initialising formatting with args {:?}", output);
+    println!(
```
Comment (jost-s) [inline crates/holochain_trace/src/lib.rs:333]: Sneaking in the modified tracing init message

File: crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs [hunk 17]
```diff
@@ -0,0 +1,296 @@
...
+                entry.get_mut().depending_ops.insert(dht_op_hash.clone());
+                false
+            }
+        }
+    }
+
+    /// Iterates over given missing hashes and adds them to the internal collection if they are not present.
+    /// A collection of new missing hashes is returned.
+    /// Takes missing hashes and the depending op as parameters.
+    pub fn insert_missing_hashes_for_op(
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow/validation_dependencies.rs:60]: I'm still not perfectly happy with this fn name because it reflects only the side-effect and not the filtering aspect of it

File: crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs [hunk 18]
```diff
@@ -469,28 +489,44 @@ async fn validation_callback_prevent_multiple_identical_hash_fetches() {
...
+    // This is sort of cheating, because it is part of what this test is supposed to ascertain. However, tests
+    // have shown that it is possible that an identical hash is fetched due to unfortunate timing:
+    // - Validate 1 fails due to missing hash, which is added to the validation dependencies and then fetched but
+    // not awaited.
+    // - Validate 2 fails as well, because the missing hash had not made it into the cache yet, but at the time of
+    // determining missing hashes to fetch, it was added to the cache and removed from validation dependencies.
+    // - With this specific sequence of events, the missing hash will be fetched again, despite being present in
+    // the cache.
+    // In real networks this should happen negligibly seldom, as network fetches will sufficiently delay a fetched
+    // missing hash from being removed from validation dependencies.
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/app_validation_workflow/run_validation_callback_tests.rs:512]: NB

**Review by ThetaSinner — APPROVED** [review]
