### PR TITLE
Fix `holochain_conductor_api` doc warnings

### LINKED ISSUE #4542: holochain_conductor_api 4 warnings

### PR DESCRIPTION
**Pull request by ThetaSinner**
### Summary

Closes  #4542

### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

File: crates/holochain_conductor_api/src/app_interface.rs [hunk 1]
```diff
@@ -548,10 +548,10 @@ pub enum ScottyPanel {
     GossipInfo { last_round: Option<Timestamp> },
 }
 
-/// The request payload that should be sent in a [`holochain_websocket::WireMessage::Authenticate`]
```
Comment (ThetaSinner) [inline crates/holochain_conductor_api/src/app_interface.rs:551]: No dependency on `holochain_websocket` here

File: crates/holochain_conductor_api/src/config/conductor/dpki_config.rs [hunk 2]
```diff
@@ -19,7 +19,8 @@ const DPKI_NETWORK_SEED_TESTING: &str = "deepkey-testing";
 ///
 /// Note that the Deepkey DNA path and the network seed settings determine network compatibility.
 /// They have to match for all conductors on a network, for them to be able to communicate.
-/// Also see [`holochain_p2p::spawn::NetworkCompatParams`].
```
Comment (ThetaSinner) [inline crates/holochain_conductor_api/src/config/conductor/dpki_config.rs:22]: No dependency on `holochain_p2p` here

**Review by mattyg — APPROVED** [review]
