### PR TITLE
fix: url format panic

### LINKED ISSUE #4170: [BUG] URL format panic
When starting up Launcher 0.300 you run into a URL format panic

[launcher.log](https://github.com/user-attachments/files/16513304/launcher.log)

[databases.zip](https://github.com/user-attachments/files/16513312/databases.zip)

```
Panic:
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"FATAL PANIC PanicInfo {"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    payload: Any { .. },"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    message: Some("}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        called `Result::unwrap()` on an `Err` value: InvalidByte(5, 46),"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    ),"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    location: Location {"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        file: \"/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kitsune_p2p_proxy-0.3.1/src/proxy_url.rs\","}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        line: 150,"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        col: 14,"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    },"}
```

### PR DESCRIPTION
**Pull request by c12i**
### Summary

This PR attempts to fix #4170, by replacing `url2!` usage with `try_url2!` in production code

Needs backport to `0.4`

### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

**Comment by ThetaSinner** [comment]
Added some more reviewers. It's good to have more people take a look if they want to, even if your'e only after one approval :)

File: crates/holochain_conductor_api/src/config/conductor.rs [hunk 1]
```diff
@@ -206,7 +206,10 @@ impl ConductorConfig {
 
     /// Check if the config is set to use a rendezvous bootstrap server
     pub fn has_rendezvous_bootstrap(&self) -> bool {
-        self.network.bootstrap_service == Some(url2::url2!("rendezvous:"))
+        match url2::try_url2!("rendezvous:") {
```
Comment (ThetaSinner) [inline crates/holochain_conductor_api/src/config/conductor.rs:209]: Can this panic? It's a known string that is a valid URL prefix

Not necessarily a bad thing to remove the panic but this does seem like an error you'd want to catch rather than just returning a boolean here if somebody made a bad edit

**Review by ThetaSinner — APPROVED** [review]
Kitsune changes look good, question about the conductor API change

**Review by neonphog — APPROVED** [review]

File: crates/holochain_conductor_api/src/config/conductor.rs (hunk 1 above)
Comment (c12i) [reply crates/holochain_conductor_api/src/config/conductor.rs]: It can't panic really, but just another infallible url2 usage I spotted, I can keep it since we are sure this won't panic. Reverted

**Review by jost-s — APPROVED** [review]
