### PR TITLE
fix: stabilize chain fork warrants

### LINKED ISSUE #5600: Stabilize chain fork warrants
Warrants are now implemented for invalid chain ops, along with blocking after warrants have been validated. The implementation of chain op warrants is thoroughly tested. However, there was less existing test coverage for chain fork warrants and limited time to add the missing coverage. So, the implementation of chain fork warrants is present but it's behind the feature flag `unstable-warrants`.

### Critical

- Add ChainFork warrant validation tests (`unit_tests.rs`)
  - `validate_chain_fork_warrant_accepted` - valid fork warrant passes validation
  - `validate_chain_fork_warrant_rejected_chain_author_mismatch` - reject when chain_author doesn't match action author
  - `validate_chain_fork_warrant_rejected_action_authors_differ` - reject when the two actions have different authors
  - `validate_chain_fork_warrant_rejected_prev_actions_differ` - reject when prev_action differs (not a real fork)
  - `validate_chain_fork_warrant_rejected_bad_signature` - reject when action signature is invalid
  - `validate_chain_fork_warrant_missing_dependency` - returns MissingDhtDep when forked action are not available

### Alternative Flows

These should use integration tests with sweettest, so the implementor should decide whether the given coverage is necessary.

- Add negative test for fork warrant issuance (tests.rs)
  - Verify no ChainFork warrant is issued when processing a valid, non-forking chain op
- Enhance sys_validation_produces_forked_chain_warrant (tests.rs)
  - Verify the action hashes in the warrant match the actual forked actions
  - Verify both signatures in the warrant are correct
- Enhance `test_detect_fork` (`tests.rs`)
  - Test behaviour with DNA action (no prev_action)
  - Verify warrant hashes in the Action table are filtered out correctly

### Final Steps

- Remove `#[cfg(feature = "unstable-warrants")]` from lines 309-312 and 318-330 in `sys_validation_workflow.rs`
- Remove `#[cfg(feature = "unstable-warrants")]` from `sys_validation_produces_forked_chain_warrant` test
- Remove `unstable-warrants` feature definition from `crates/holochain/Cargo.toml`
- `detect_fork` doesn't actually need to be public.

AC:
- [ ] Test coverage for chain fork warrants has been assessed and more tests have been added as required.
- [ ] Chain fork warrants are no longer behind the feature flag `unstable-warrants`.
- [ ] Dev portal updated to mention that chain fork warrants are implemented.
- [x] Feature flag `unstable-warrants` is removed.

### PR DESCRIPTION
**Pull request by veeso**
### Summary

Stabilize the chain fork warrants feature by removing the unstable-warrants feature gate and adding comprehensive test coverage. Additionally, add `seq` validation to `ChainFork` warrants so that the sequence number is checked during warrant verification.

Changes:

- Remove `unstable-warrants` feature gate from chain fork warrant code paths
- SQL query (`action_hash_by_prev.sql`): do not filter by author in the query, check after the query and raise an error if it doesn't match
- Add `seq` field to `ChainIntegrityWarrant::ChainFork` and populate it from the detected fork's action sequence number
- Refactor `ForkedPair` from a nested tuple to a named struct for clarity
- Validate `seq` during warrant verification with the following check order:
  1. One or both action hashes can't be found → can't validate (MissingDhtDep)
  2. `chain_author` doesn't match action author → reject
  3. Actions authored by different agents → reject
  4. Actions have different sequence numbers (not a fork) → reject
  5. Sequence numbers match but don't match the warrant's `seq` → reject
  6. Actions don't share a `prev_action` (not a fork) → reject
  7. Everything matches → accept
- Add unit tests for `validate_warrant_op` covering `ChainFork` warrant validation:
  - Accepted: valid warrant with matching authors, seq, and prev_actions
  - Rejected: chain_author mismatch
  - Rejected: action authors differ
  - Rejected: action sequence numbers differ
  - Rejected: warrant seq doesn't match actions' seq
  - Rejected: prev_actions differ (not a real fork)
  - MissingDependencies: when forked actions aren't available
- Enhance integration tests (`sys_validation_produces_forked_chain_warrant`, `sys_validation_produces_two_warrants_when_receiving_both_forked_ops`) to verify the warrant's `seq` and action_pair contain correct values
- Enhance `test_detect_fork` with explicit test for DNA actions (no prev_action)

Closes #5600

### TODO:
- [x] CHANGELOGs updated with appropriate info
- [x] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs [hunk 1]
```diff
@@ -193,10 +198,27 @@ async fn sys_validation_produces_forked_chain_warrant() {
...
+                        hashes.contains(&original_action_hash),
+                        "Warrant should contain original action hash"
+                    );
+                    assert!(
+                        hashes.contains(&forked_action_hash),
+                        "Warrant should contain forked action hash"
+                    );
+                }
+                _ => panic!("Expected ChainFork warrant"),
+            }
```
Comment (mattyg) [inline crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:251]: It might be good to test that another peer who receives both ops, then runs sys validation, creates 2 chain fork warrants.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs
Comment (mattyg) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs:1584]: This sql query doesn't filter only actions with a matching author, but we validate that the warrant contains two actions with matching authors.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_op_tests.rs [hunk 2]
```diff
@@ -2395,3 +2396,362 @@ fn test_op(previous: &SignedHashed<Action>) -> DhtOp {
 
     ChainOp::RegisterAgentActivity(fixt!(Signature), action).into()
 }
+
+// ============================================================================
+// ChainFork Warrant Validation Tests
+// ============================================================================
```
Comment (mattyg) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validate_op_tests.rs]: Nitpick that if we need a comment to distinguish this section, we might just move it into another file.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs
Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs:1584]: I don't know if it was what you meant, but I've added a test for covering that case.

**Comment by veeso** [comment]
> There are a few comments in the codebase that say "Chain fork detection is not considered stable at this time."
> 
> Just to confirm -- have get_agent_activity and must_get_agent_activity been reviewed to make sure they behave as expected with this change? Do we have tests for it? If not these may need to be separate PRs in which case I suggest we not stabilize the feature until that is done.

There are no concerning about stability. I just didnd't see them. I've now removed those comments.

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs (hunk 1 above)
Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:251]: implemented a test for that.

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs
Comment (mattyg) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs:1584]: I mean that this query can return an action with a different author, which would cause you to author an invalid warrant.

Also this query doesn't ensure that the prev action has any associated DhtOps that are valid. Is that right?

Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs:1584]: @mattyg Got it, you're right. I've changed the query.

File: crates/holochain/CHANGELOG.md [hunk 3]
```diff
@@ -8,6 +8,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 ## Unreleased
 
 - Added `deny_unknown_fields` to conductor configuration structs to improve UX by rejecting configurations with typos or obsolete fields. This helps catch configuration errors early. #5455
+- Stabilized chain fork warrants that were previously behind the `unstable-warrants` feature; the feature has now been removed. #5641
```
Comment (ThetaSinner) [inline crates/holochain/CHANGELOG.md]:
```suggestion
- Stabilized chain fork warrants that were previously behind the `unstable-warrants` feature; the feature has now been removed. #5641
- Added `deny_unknown_fields` to conductor configuration structs to improve UX by rejecting configurations with typos or obsolete fields. This helps catch configuration errors early. #5455
```

Minor thing, please stack new entries on top

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs [hunk 4]
```diff
@@ -1546,16 +1543,17 @@ pub async fn make_fork_warrant_op_inner(
...
     action: &Action,
 ) -> StateQueryResult<Option<(ActionHash, Signature)>> {
-    let mut statement = txn.prepare(ACTION_HASH_BY_PREV)?;
+    let mut statement = txn.prepare(ACTION_HASH_BY_PREV_AND_AUTHOR)?;
     let items = statement
         .query_map(
             named_params! {
                 ":prev_hash": action.prev_action(),
                 ":hash": action.to_hash(),
+                ":author": action.author(),
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow.rs]: I think you're working to cover a case that was missed here - but I'm wondering how this now behaves. If somebody authors a chain fork warrant but references actions from different authors, then the warrant is clearly invalid. I'm wondering if this query should actually  `SELECT seq, author` from the database and check the author's match. If they don't, the warrant can be rejected?

Otherwise, I think the warrant fails to validate here if the `seq` can't be looked up?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs [hunk 5]
```diff
@@ -0,0 +1,443 @@
...
+                "Expected 'chain author mismatch' in rejection reason, got: {reason}"
+            );
+        }
+        _ => panic!("Expected Rejected outcome but got: {outcome:?}"),
+    }
+}
+
+/// Test that a ChainFork warrant is rejected when the two actions have different authors
+#[tokio::test(flavor = "multi_thread")]
+async fn validate_chain_fork_warrant_rejected_action_authors_differ() {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: How is this different to the test above?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs [hunk 6]
```diff
@@ -0,0 +1,443 @@
...
+        _ => panic!("Expected Rejected outcome but got: {outcome:?}"),
+    }
+}
+
+// Note: Testing bad action signatures within a ChainFork warrant is not covered here because:
+// 1. Warrants with bad warrant-level signatures are caught by `verify_warrant_signature` before
+//    they reach `validate_warrant_op` in the sys validation workflow
+// 2. Bad action signatures within the warrant would hit the unreachable code path for
+//    `CounterfeitAction` since counterfeit ops are expected to be filtered before sys validation
+// The signature verification for actions in warrants is still exercised by the valid warrant test.
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: That's valid. I wonder if this would be better as a doc comment at the top of the file rather than floating here?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs [hunk 7]
```diff
@@ -0,0 +1,443 @@
...
+
+/// Test that a ChainFork warrant is rejected when the action pair has different authors.
+///
+/// Note: `detect_fork` now filters by author in its SQL query, so cross-author collisions
+/// will not produce warrants in practice. This test verifies defense-in-depth: even if a
+/// cross-author warrant were somehow constructed, the warrant validation correctly rejects it.
+#[tokio::test(flavor = "multi_thread")]
+async fn validate_chain_fork_warrant_rejected_cross_author_collision() {
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: Difference from the tests above? Either the two actions don't match each other, or the warranted agent didn't author one or both of the referenced actions - what is this third case about?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs [hunk 8]
```diff
@@ -0,0 +1,443 @@
...
+
+    let outcome = test_case.validate_warrant(warrant_op).await.unwrap();
+
+    assert!(
+        matches!(outcome, Outcome::Accepted),
+        "Expected Accepted but actual outcome was {outcome:?}"
+    );
+}
+
+/// Test that a ChainFork warrant is rejected when chain_author doesn't match action1's author
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: The text in the issue could have been improved. Perhaps expand the wording here to something like "The author being warranted is not the author of at least one of the referenced actions"

**Review by ThetaSinner — COMMENTED** [review]
Looking good! I have quite minor feedback on this one:
- Question about how mismatched chain authors is being handled - given the testing, it should be working - but I can't immediately see why from the code so perhaps it justifies a code comment or just a quick description here so I can get the understanding?
- Some minor comments about test descriptions and the changelog.

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs [hunk 9]
```diff
@@ -193,10 +198,189 @@ async fn sys_validation_produces_forked_chain_warrant() {
...
+    let op1_hashed = DhtOpHashed::from_content_sync(op1);
+    let op2_hashed = DhtOpHashed::from_content_sync(op2);
+    let db = conductor.spaces.dht_db(dna.dna_hash()).unwrap();
+    db.test_write(move |txn| {
+        insert_op_dht(txn, &op1_hashed, 0, None).unwrap();
+        insert_op_dht(txn, &op2_hashed, 0, None).unwrap();
+    });
+
+    // Check that Bob authored 2 chain fork warrants
+    crate::wait_for_1m!(
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs]: FYI, there is a simpler macro called `retry_until_timeout` and a function `retry_fn_until_timeout` in the test utils that are more widely used. Personally I prefer them and further I think there shouldn't be such a variety of helper macros that all accomplish more or less the same thing. You don't need to change this here, but just so you know.

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs [hunk 10]
```diff
@@ -193,10 +198,189 @@ async fn sys_validation_produces_forked_chain_warrant() {
...
+                .unwrap()
+                .test_read(move |txn| {
+                    let store = CascadeTxnWrapper::from(txn);
+                    store.get_warrants_for_agent(&alice_pubkey, false).unwrap()
+                })
+        },
+        |warrants: &Vec<WarrantOp>| { warrants.len() == 2 },
+        |warrants: Vec<WarrantOp>| {
+            // Verify we have exactly 2 warrants
+            assert_eq!(warrants.len(), 2, "Expected 2 chain fork warrants");
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:391]: This is a redundant check, as the previous condition does exactly that. It'd be different if you read all warrants from the DB again.

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs [hunk 11]
```diff
@@ -193,10 +198,189 @@ async fn sys_validation_produces_forked_chain_warrant() {
...
+                    _ => panic!("Expected ChainFork warrant"),
+                }
+            }
+
+            // Both warrants should reference the same pair of forked actions
+            assert!(
+                all_hashes.contains(&action1_hash),
+                "Warrants should contain action1 hash"
+            );
+            assert!(
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:418]: And the previous action for completeness?

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 4 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: For the current implementation this behaves as intended, I think. Chain fork warrant validation checks if the authors of referenced actions are the same. If not, the warrant is invalid. That's what this query looks for too, forked actions by the same author. What is the `seq`'s role here?

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs [hunk 12]
```diff
@@ -193,10 +198,189 @@ async fn sys_validation_produces_forked_chain_warrant() {
...
+    let mut dna_action = fixt!(Dna);
+    dna_action.author = alice_pubkey.clone();
+    let dna_action = Action::Dna(dna_action);
+    let signed_dna_action = SignedActionHashed::sign(&keystore, dna_action.into_hashed())
+        .await
+        .unwrap();
+    let prev_action_hash = signed_dna_action.as_hash().clone();
+
+    // Create two forked actions that both point to the same prev_action
+    let entry1 = Entry::App(AppEntryBytes(UnsafeBytes::from(vec![1; 10]).into()));
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:287]: Another FYI, you can use a fixturator for this `Entry::App(fixt!(AppEntryBytes))`

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 4 above)
Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: I don't get what the use of `seq` would be then though

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs [hunk 13]
```diff
@@ -170,35 +176,218 @@ async fn sys_validation_produces_forked_chain_warrant() {
...
+
+            // Both warrants should reference the same pair of forked actions
+            assert!(
+                all_hashes.contains(&action1_hash),
+                "Warrants should contain action1 hash"
+            );
+            assert!(
+                all_hashes.contains(&action2_hash),
+                "Warrants should contain action2 hash"
+            );
```
Comment (jost-s) [inline crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:421]: I meant
```suggestion
            assert!(
                all_hashes.contains(&action2_hash),
                "Warrants should contain action2 hash"
            );
            assert!(
                all_hashes.contains(&prev_action_hash),
                "Warrants should contain previous action hash"
            );
```

**Review by jost-s — APPROVED** [review]
Great you immediately switched to the simpler retry macros.

LGTM

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs (hunk 13 above)
Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:421]: The ChainFork warrant's action_pair contains only the two conflicting forked actions (action1_hash and action2_hash). The prev_action_hash (their common predecessor — the
  DNA genesis action) is not stored in the warrant. It's used implicitly by detect_fork to find actions that share a common predecessor, and it's checked during warrant validation (line 1096:
  action1.prev_action() != action2.prev_action()), but the hash itself never appears in the warrant's action_pair field.
  
So this check is not correct

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 4 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: The chain of actions is formed by creating new actions where `seq = seq + 1` and the `prev_hash` references the previous action. The chain forks when two actions have the same `prev_hash` and the same `seq` value.

The cases we're dealing with for a chain fork warrant then are:
1. One or both of the referenced action hashes can't be found -> can't validate the warrant
2. The identified actions are authored by two different agents and are therefore not a fork -> reject the warrant
3. The identified actions have different sequence numbers, one of which must be invalid data because the seq must increment by exactly `1` from its previous action, but it's not a fork -> reject the warrant
4. The sequence numbers of the actions match but aren't the same as the sequence number in the warrant -> reject the warrant and we may end up issuing our own.
5. The two identified actions don't share a `prev_hash`, therefore not a fork -> reject the warrant
6. Everything matches, the identified actions are by the same author and share a `prev_hash` and sequence number as identified in the warrant -> accept the warrant and block the author of the fork.

What I'm concerned about here is case 1 being wrongly identified. If we filter on the author, we risk not looking up information that we'd need to determine that the warrant is actually invalid.

Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: > Chain fork warrant validation checks if the authors of referenced actions are the same. If not, the warrant is invalid

I agree, I just want to be sure that the code is doing exactly that. Looking up the author rather than filtering on it in the query.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs (hunk 6 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: This appears to just have become attached to the test below? I was meaning a module level doc comment rather than attaching it to the next test. I don't think it's actually related to the next test right?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs (hunk 7 above)
Comment (ThetaSinner) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: What was the resolution here? I see the test name no longer appears but is it removed or changed?

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 4 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: The additional cases to identify invalid warrants are good to catch. I hadn't thought of them.

The current implementation of detecting forks doesn't consider the sequence. If the author of the forked actions is identical, their previous action hashes are identical, does it matter that the seq is identical too? In a system where hash collisions are not considered, I think it can be neglected.

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs (hunk 7 above)
Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs]: It was removed because it was not necessary

File: crates/holochain/src/core/workflow/sys_validation_workflow.rs (hunk 4 above)
Comment (veeso) [reply crates/holochain/src/core/workflow/sys_validation_workflow.rs]: I've added `seq` check, but I don't think it was strictly necessary, but just an additional check

File: crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs (hunk 13 above)
Comment (jost-s) [reply crates/holochain/src/core/workflow/sys_validation_workflow/tests.rs:421]: Ah yes, of course, my mistake.

Actually I think this test case highlights a minor problem with the fork detection logic. When two actions with the same previous action hash arrive at the same time at the conductor, there's no way of telling whether one is valid or not. Luckily the query is checking for the same author now, which neutralizes the problem largely, because it can only be two actions signed by the same author that lead to a fork.
Without this check an attacker could just send valid actions along with forked actions and both would lead to warrants on the receiving conductors.

**Review by ThetaSinner — CHANGES_REQUESTED** [review]
This isn't what I was after. The database query now filters on author AND seq - but I was asking why we weren't removing the author filter. I don't understand how you can filter on those fields in the database and still retrieve mismatched data to see that the warrant is invalid?

File: crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs [hunk 14]
```diff
@@ -0,0 +1,373 @@
...
+    // Insert dependencies
+    test_case.insert_action_dependency(&action1);
+    test_case.insert_action_dependency(&action2);
+
+    let outcome = test_case.validate_warrant(warrant_op).await.unwrap();
+
+    match outcome {
+        Outcome::Rejected(reason) => {
+            assert!(
+                reason.contains("action pair seq mismatch"),
```
Comment (ThetaSinner) [inline crates/holochain/src/core/workflow/sys_validation_workflow/validate_warrant_tests.rs:202]: They have the same sequence number of 5, but a different `prev_hash` - unexpected error message?

**Review by ThetaSinner — APPROVED** [review]
